// Contenus du prototype — Bénin.
// Les coordonnées GPS sont approximatives et doivent être relevées sur place
// avant l'impression des QR codes.

module.exports = [
  {
    id: 1,
    slug: "palais-royaux-abomey",
    country: "Bénin",
    cat: "historique",
    name: "Palais royaux d'Abomey",
    region: "Zou, Abomey",
    featured: true,
    latitude: 7.183,
    longitude: 1.991,
    radius: 400,
    themes: ["royaumes", "architecture", "artisanat", "resistances"],
    description: "Pendant près de trois siècles, Abomey fut la capitale du Danxomè, l'un des royaumes les plus puissants et les mieux organisés d'Afrique de l'Ouest. Au cœur de la ville, une vaste enceinte de murs de terre rouge abrite les palais que les rois ont fait bâtir les uns à côté des autres, chacun marquant son règne par son propre palais.\n\nClassés au patrimoine mondial de l'UNESCO, les palais racontent, à travers leurs bas-reliefs, leurs trônes, leurs tentures et leurs récits, l'histoire d'un État africain souverain, de sa puissance militaire, de ses arts de cour et de sa résistance à la conquête coloniale.",
    histoire: "### Les origines d'un royaume\nLa tradition fait remonter la dynastie à des princes venus d'Allada, au sud, au début du XVIIe siècle. Ils s'installent sur le plateau d'Abomey, où règnent alors des chefs locaux. Le roi Houégbadja, qui règne dans la seconde moitié du XVIIe siècle, est considéré comme le véritable fondateur du royaume et de sa capitale : c'est à lui que la tradition attribue la construction du premier grand palais.\n\n### Une capitale bâtie roi après roi\nUne règle marque l'histoire d'Abomey : chaque nouveau roi fait construire son propre palais, à côté de celui de son prédécesseur, sans détruire les anciens. L'enceinte royale s'agrandit ainsi au fil des règnes et finit par couvrir une quarantaine d'hectares, entourés de murs de terre. Les palais comprennent des cours successives, des salles de réception, des logements pour les épouses et les serviteurs, des greniers, des temples et les tombeaux des rois.\n\n### De l'intérieur des terres à la mer\nAu XVIIIe siècle, le roi Agadja étend le royaume vers la côte : il conquiert Allada (1724) puis le royaume Xwéda et son port, Ouidah (1727). Le Danxomè contrôle désormais l'accès à l'océan et au commerce atlantique, y compris la traite des captifs, qui marque profondément son histoire et celle de toute la région. Au XIXe siècle, les rois Ghézo (1818-1858) puis Glèlè (1858-1889) renforcent l'État, l'armée — dont le célèbre corps des Agojie — et développent l'économie de l'huile de palme.\n\n### Guerre, incendie et exil\nÀ la fin du XIXe siècle, la France veut imposer son autorité sur la côte. Le roi Béhanzin (1889-1894) résiste pendant deux guerres, en 1890 puis en 1892. Lorsque les troupes coloniales approchent d'Abomey en novembre 1892, une grande partie des palais est incendiée — plusieurs sources indiquent que Béhanzin lui-même ordonna l'incendie pour ne pas livrer la capitale. Il poursuit la lutte jusqu'à sa reddition en janvier 1894 ; il est ensuite exilé en Martinique, puis en Algérie, où il meurt en 1906. De nombreux objets royaux sont emportés en France comme butin de guerre.\n\n### Patrimoine mondial et restitutions\nUne partie des palais, dont ceux de Ghézo et de Glèlè, accueille le Musée historique d'Abomey. En 1985, les palais sont inscrits sur la liste du patrimoine mondial de l'UNESCO et, la même année, sur la liste du patrimoine en péril, après les dégâts d'une tornade ; d'importants travaux de conservation permettent de les en retirer en 2007. En novembre 2021, la France restitue au Bénin 26 œuvres du trésor royal d'Abomey — trônes, statues royales, portes sculptées —, présentées l'année suivante à Cotonou devant un très large public. Un moment fort de réappropriation de ce patrimoine par les Béninois.",
    culture: "Les palais ne sont pas seulement un musée : ils restent un lieu vivant de la mémoire du Danxomè. Les familles royales y célèbrent encore des cérémonies en l'honneur des ancêtres, et la légitimité des collectivités familiales issues des rois s'y enracine.\n\nLes bas-reliefs forment une véritable bibliothèque d'argile. Chaque roi y a fait représenter ses emblèmes, ses « noms forts » et ses hauts faits : batailles, alliances, proverbes. Lire ces murs, c'est lire l'histoire politique du royaume telle qu'elle a été racontée par le royaume lui-même, et non par ses conquérants.\n\nPour les Béninois, Abomey est aussi un symbole de souveraineté et de résistance : la figure de Béhanzin, refusant de se soumettre, est au cœur de la mémoire nationale.",
    savoirs: "### L'art de bâtir en terre\nLes murs sont faits de terre (banco) mélangée et montée en couches successives, puis enduits. Ce savoir-faire exige un entretien régulier, transmis de génération en génération : c'est lui qui a permis de conserver et de restaurer les palais.\n\n### Les bas-reliefs polychromes\nModelés dans la terre des murs, puis peints, les bas-reliefs représentent animaux, armes et scènes symboliques. Leur restauration, menée avec des artisans héritiers de ces techniques, est l'une des grandes réussites de la conservation du site.\n\n### Les tentures appliquées\nLes tentures en appliqué — motifs de tissu colorés cousus sur un fond uni — racontaient les règnes et les devises des rois. Des familles d'artisans d'Abomey perpétuent cet art, aujourd'hui décliné sur toutes sortes de supports.\n\n### Les arts de cour\nForgerons, sculpteurs, orfèvres et tisserands travaillaient pour la cour, organisés en corporations. Les récades (sceptres royaux), les trônes et les statues royales témoignent de ce raffinement.",
    communities: "Musée historique d'Abomey, familles royales d'Abomey, artisans héritiers des corporations de cour (tisserands d'appliqués, forgerons, sculpteurs).",
    langues: "Fon, français",
    personnalites: "Roi Houégbadja (fondateur de la capitale) ; roi Agadja (conquête d'Allada et de Ouidah) ; roi Ghézo (1818-1858) ; roi Glèlè (1858-1889) ; roi Béhanzin (1889-1894), figure de la résistance à la conquête coloniale ; les Agojie, guerrières du royaume.",
    infos_pratiques: "Visite guidée du Musée historique d'Abomey sur place (horaires et tarifs à confirmer auprès du musée). Prévoir 1 h 30 à 2 h pour le musée et les bas-reliefs, davantage pour découvrir la ville. Abomey est à environ 2 h 30 de route de Cotonou. Photographies parfois limitées à l'intérieur : se renseigner à l'accueil.",
    chronologie: [
      ["Début du XVIIe siècle", "Selon la tradition, des princes venus d'Allada s'installent sur le plateau d'Abomey."],
      ["Seconde moitié du XVIIe siècle", "Règne de Houégbadja, considéré comme le fondateur du royaume et de la capitale."],
      ["1724", "Le roi Agadja conquiert le royaume d'Allada."],
      ["1727", "Conquête de Ouidah : le Danxomè accède à la mer et au commerce atlantique."],
      ["1818-1858", "Règne de Ghézo : réformes de l'État et de l'armée."],
      ["1858-1889", "Règne de Glèlè."],
      ["1890 et 1892", "Guerres contre la France sous le règne de Béhanzin."],
      ["Novembre 1892", "Incendie d'une grande partie des palais à l'arrivée des troupes coloniales."],
      ["Janvier 1894", "Reddition de Béhanzin, exilé en Martinique puis en Algérie."],
      ["1985", "Inscription au patrimoine mondial de l'UNESCO (et sur la liste en péril jusqu'en 2007)."],
      ["Novembre 2021", "Restitution par la France de 26 œuvres du trésor royal d'Abomey."]
    ],
    a_voir: [
      ["Les bas-reliefs", "Sur les murs des palais, des dizaines de bas-reliefs peints racontent les emblèmes et les hauts faits des rois : prendre le temps de les faire expliquer par un guide."],
      ["Le Musée historique", "Installé dans les palais de Ghézo et de Glèlè : trônes, récades, armes, tentures et objets de la vie de cour."],
      ["Les tombeaux royaux", "Les cases funéraires des rois, lieux de mémoire toujours respectés."],
      ["Les ateliers d'appliqués", "En ville, des artisans perpétuent l'art des tentures appliquées : un bon moyen de soutenir l'économie locale."],
      ["La place Goho", "À l'entrée de la ville, la statue de Béhanzin rappelle le roi résistant."]
    ],
    saviez_vous: ["Un roi a été effacé de la liste officielle : Adandozan, renversé en 1818 par Ghézo. Pendant longtemps, son nom n'était pas prononcé dans les récits de la cour.", "Chaque roi choisissait un « nom fort », une sorte de devise imagée. Celui de Béhanzin évoque le requin qui trouble la barre, face aux ennemis venus de la mer."],
    sources: ["UNESCO — Centre du patrimoine mondial, « Palais royaux d'Abomey » (inscription 1985)", "Maurice Ahanhanzo Glèlè, Le Danxomè. Du pouvoir aja à la nation fon, 1974", "Musée historique d'Abomey", "Restitution de 26 œuvres du trésor royal d'Abomey (novembre 2021)"],
    recits: [
      { title: "Les emblèmes des rois", nature: "tradition_orale", body: "La tradition rapporte que chaque roi, à son intronisation, choisissait un « nom fort » et un emblème qui résumaient sa devise. Houégbadja est associé au poisson qui a échappé à la nasse, Ghézo au buffle, Glèlè au lion et Béhanzin au requin, qui trouble les eaux et défie ceux qui viennent de la mer. Ces symboles se retrouvent sur les bas-reliefs, les tentures et les récades (sceptres) royales." },
      { title: "Danxomè, « dans le ventre de Dan »", nature: "tradition_orale", body: "Une tradition célèbre explique le nom du royaume. Un chef local, Dan, se serait moqué des ambitions du nouveau venu en lui demandant s'il comptait bâtir sa maison sur son ventre. Vaincu, Dan aurait été enseveli sous les fondations du palais, qui prit le nom de Danxomè : « dans le ventre de Dan ». Comme tous les récits de fondation, il existe plusieurs versions de cette histoire, transmises par les familles et les héraldistes de la cour." }
    ],
    quiz: [
      { question: "En quelle année les palais royaux d'Abomey ont-ils été inscrits au patrimoine mondial de l'UNESCO ?", choices: ["1960", "1985", "2005"], answer: 1, explanation: "Les palais royaux d'Abomey sont inscrits sur la liste du patrimoine mondial depuis 1985." },
      { question: "Quel animal est l'emblème du roi Béhanzin ?", choices: ["Le requin", "L'éléphant", "L'aigle"], answer: 0, explanation: "Béhanzin est associé au requin, symbole de résistance face à ceux qui venaient de la mer." },
      { question: "En quelle année la France a-t-elle restitué au Bénin 26 trésors royaux d'Abomey ?", choices: ["1960", "1992", "2021"], answer: 2, explanation: "La restitution a eu lieu en novembre 2021, près de 130 ans après le pillage de 1892." },
      { question: "Quel roi a donné au Danxomè l'accès à la mer en conquérant Ouidah ?", choices: ["Agadja", "Glèlè", "Béhanzin"], answer: 0, explanation: "Le roi Agadja conquiert Allada en 1724 puis Ouidah en 1727." },
      { question: "Quelle règle explique qu'il y ait plusieurs palais à Abomey ?", choices: ["Chaque roi faisait bâtir son propre palais", "Chaque province avait son palais", "Les palais étaient reconstruits chaque siècle"], answer: 0, explanation: "Chaque nouveau roi faisait construire son palais à côté de celui de son prédécesseur, sans détruire les anciens." }
    ]
  },
  {
    id: 2,
    slug: "ganvie",
    country: "Bénin",
    cat: "culturel",
    name: "Cité lacustre de Ganvié",
    region: "Atlantique, Sô-Ava, lac Nokoué",
    featured: true,
    latitude: 6.466,
    longitude: 2.418,
    radius: 1500,
    themes: ["eaux", "memoire-traite", "marches", "gastronomie"],
    description: "Au nord de Cotonou, au milieu du lac Nokoué, des milliers de maisons sur pilotis forment l'une des plus grandes cités lacustres d'Afrique : Ganvié. On y circule en pirogue, on y fait son marché sur l'eau, on y va à l'école, à l'église ou à la mosquée sans jamais toucher la terre ferme.\n\nSurnommée la « Venise de l'Afrique », Ganvié est d'abord une histoire de refuge et d'adaptation : celle du peuple toffin, qui a fait de l'eau son rempart, puis son monde.",
    histoire: "### Un refuge sur l'eau\nSelon la tradition, les ancêtres des Toffinu vivaient sur la terre ferme, au nord du lac. Aux XVIIe et XVIIIe siècles, les razzias menées par le royaume du Danxomè pour capturer des populations et les vendre aux négriers européens menacent la région. Pour y échapper, les Toffinu se réfugient sur le lac Nokoué. L'eau les protège : une interdiction religieuse empêchait les guerriers du Danxomè de s'aventurer sur le lac.\n\n### Un nom qui dit la paix retrouvée\nLe nom de Ganvié est généralement traduit par « la communauté a trouvé la paix » ou « nous sommes sauvés ». Il résume l'histoire de sa fondation : une communauté qui a survécu à la traite en inventant une nouvelle manière de vivre.\n\n### De la pêche à la ville sur pilotis\nAu fil des générations, le village s'étend. Les habitants développent des techniques de pêche adaptées au lac, notamment les acadjas, et un commerce actif avec les marchés des rives. Ganvié devient une véritable ville d'eau, qui compte aujourd'hui plusieurs dizaines de milliers d'habitants, avec ses quartiers, ses écoles, ses lieux de culte et son marché flottant.\n\n### Aujourd'hui\nGanvié fait partie de la commune de Sô-Ava. Elle figure sur la liste indicative du Bénin pour le patrimoine mondial de l'UNESCO. La cité fait face à de grands défis : pollution et envasement du lac, prolifération de la jacinthe d'eau, pression du tourisme, accès à l'eau potable et à l'assainissement. Des projets d'aménagement cherchent à améliorer les conditions de vie tout en préservant l'identité du lieu.",
    culture: "Ganvié est un symbole de résistance : ici, la mémoire de la traite ne se raconte pas seulement dans les musées, elle s'inscrit dans le paysage. Chaque maison sur pilotis rappelle que des familles ont choisi l'eau pour rester libres.\n\nLa vie sociale est entièrement organisée autour du lac. Les femmes tiennent une place centrale dans le commerce : depuis leurs pirogues chargées de poissons, de fruits, d'épices ou de charbon, elles animent le marché flottant et relient la cité aux marchés des rives. Les enfants apprennent très tôt à manier la pagaie.\n\nLes Toffinu entretiennent aussi des lieux de culte liés à l'eau et à leurs ancêtres, qui rappellent le lien spirituel entre la communauté et le lac.",
    savoirs: "### Construire sur l'eau\nLes maisons reposent sur des pilotis de bois plantés dans le fond du lac, avec des planchers et des murs en bois ou en bambou, et des toits autrefois en paille. Elles doivent résister au vent, aux crues et à l'humidité : un savoir-faire transmis entre charpentiers.\n\n### Les acadjas\nL'acadja est un enclos de branchages planté dans le lac. Les poissons s'y abritent, s'y nourrissent et s'y reproduisent ; on les récolte ensuite. Cette technique de pisciculture traditionnelle, très ingénieuse, doit être bien gérée pour ne pas épuiser le lac.\n\n### La pirogue et la pêche\nFabrication et entretien des pirogues, maniement de la pagaie et de la perche, filets, nasses : toute la vie dépend de ces savoirs. Le fumage du poisson, souvent assuré par les femmes, permet de le conserver et de le vendre sur les marchés.",
    communities: "Communauté toffin de Ganvié, piroguiers et guides locaux, commerçantes du marché flottant, commune de Sô-Ava.",
    langues: "Toffin, fon, français",
    personnalites: "—",
    infos_pratiques: "Accès en pirogue à moteur ou à pagaie depuis l'embarcadère d'Abomey-Calavi (environ 30 à 45 minutes). Réserver auprès d'un guide agréé et convenir du tarif avant de partir. Prévoir une protection contre le soleil. Demander l'autorisation avant de photographier les habitants : Ganvié est un lieu de vie, pas un décor.",
    chronologie: [
      ["XVIIe - XVIIIe siècles", "Pour fuir les razzias liées à la traite, les ancêtres des Toffinu s'installent sur le lac Nokoué."],
      ["XIXe - XXe siècles", "Le village grandit et devient une véritable ville sur pilotis, vivant de la pêche et du commerce."],
      ["Années 1990", "Inscription sur la liste indicative du Bénin pour le patrimoine mondial de l'UNESCO."],
      ["Aujourd'hui", "Plusieurs dizaines de milliers d'habitants ; enjeux de pollution, d'envasement et d'aménagement."]
    ],
    a_voir: [
      ["Le marché flottant", "Le matin, les commerçantes vendent depuis leurs pirogues : poissons, fruits, épices, produits du quotidien."],
      ["Les acadjas", "Ces enclos de branchages plantés dans le lac révèlent l'ingéniosité de la pêche toffin."],
      ["Les maisons sur pilotis", "Observer la diversité des constructions, des plus anciennes aux plus récentes."],
      ["Les ateliers de pirogues", "Rencontrer les artisans qui fabriquent et réparent les embarcations."]
    ],
    saviez_vous: ["À Ganvié, on se rend à l'école, au marché ou à la prière en pirogue : l'eau remplace les rues.", "La jacinthe d'eau, une plante invasive, envahit parfois le lac : certaines initiatives locales la transforment en compost ou en objets artisanaux."],
    sources: ["Agence nationale de promotion des patrimoines et de développement du tourisme (ANPT, Bénin)", "UNESCO — Liste indicative du Bénin, Cité lacustre de Ganvié", "Commune de Sô-Ava"],
    recits: [
      { title: "Pourquoi sur l'eau ?", nature: "tradition_orale", body: "On raconte que les ancêtres des Toffinu, poursuivis par les guerriers du Danxomè, trouvèrent refuge sur les eaux du lac Nokoué. Les guerriers, liés par un interdit religieux, ne pouvaient pas entrer dans l'eau. Les réfugiés y bâtirent leurs maisons et donnèrent au lieu un nom qui célèbre la paix retrouvée. Cette histoire rappelle que la traite a transformé les paysages et les modes de vie jusqu'à l'intérieur des terres." },
      { title: "La pagaie avant la marche", nature: "recit_communautaire", body: "À Ganvié, on aime dire que les enfants savent tenir une pagaie presque avant de savoir marcher. Dès le plus jeune âge, ils se déplacent seuls en petite pirogue pour aller à l'école ou rendre visite à leurs voisins : une autonomie qui étonne souvent les visiteurs." }
    ],
    quiz: [
      { question: "Sur quel lac la cité de Ganvié est-elle construite ?", choices: ["Le lac Ahémé", "Le lac Nokoué", "Le lac Tchad"], answer: 1, explanation: "Ganvié est bâtie sur pilotis au milieu du lac Nokoué, au nord de Cotonou." },
      { question: "Qu'est-ce qu'un « acadja » ?", choices: ["Une pirogue de cérémonie", "Un enclos de branchages pour la pêche", "Un marché de nuit"], answer: 1, explanation: "L'acadja est un enclos de branchages planté dans le lac : les poissons s'y abritent et s'y reproduisent." },
      { question: "Pourquoi les Toffinu se sont-ils installés sur l'eau, selon la tradition ?", choices: ["Pour fuir les razzias du Danxomè", "Pour se rapprocher des marchés européens", "À cause d'une sécheresse"], answer: 0, explanation: "L'eau les protégeait des razzias : un interdit empêchait les guerriers du Danxomè d'entrer dans le lac." },
      { question: "Comment traduit-on généralement le nom « Ganvié » ?", choices: ["La ville des pêcheurs", "La communauté a trouvé la paix", "L'eau qui brille"], answer: 1, explanation: "Ganvié est souvent traduit par « la communauté a trouvé la paix » ou « nous sommes sauvés »." },
      { question: "Quel comportement adopter en visitant Ganvié ?", choices: ["Photographier librement les habitants", "Demander l'autorisation avant de photographier", "Lancer des bonbons aux enfants"], answer: 1, explanation: "Ganvié est un lieu de vie : on demande toujours l'accord des personnes avant de les photographier." }
    ]
  },
  {
    id: 3,
    slug: "foret-sacree-kpasse",
    country: "Bénin",
    cat: "savoirs",
    name: "Forêt sacrée de Kpassè",
    region: "Atlantique, Ouidah",
    featured: false,
    latitude: 6.3627,
    longitude: 2.0822,
    radius: 300,
    themes: ["spiritualites", "faune-flore", "royaumes"],
    description: "En plein cœur de Ouidah, à quelques minutes du temple des Pythons, s'étend un îlot de grands arbres : la forêt sacrée de Kpassè. On y entre par un portail gardé par une statue de Legba, et l'on découvre, à l'ombre des irokos, un lieu de culte vodun peuplé de sculptures représentant les divinités.\n\nLa forêt porte le nom du roi Kpassè, considéré comme le fondateur de la ville. Elle rappelle que, dans la culture vodun, certains lieux naturels sont sacrés — et que ce caractère sacré les a protégés jusqu'à aujourd'hui.",
    histoire: "### Le roi Kpassè et la fondation de Ouidah\nAvant de devenir le port du Danxomè, Ouidah (Glexwe) appartenait au royaume Xwéda (Houéda), dont la capitale était Savi, un peu plus au nord. La tradition présente Kpassè comme le fondateur de la ville, au XVIIe siècle. Il y aurait installé sa résidence, et la forêt qui porte son nom serait liée à son histoire et à sa disparition.\n\n### Une forêt préservée par le sacré\nAu fil des siècles, alors que la ville grandissait autour d'elle, la forêt a été préservée grâce aux interdits religieux : on n'y coupe pas les arbres, on n'y chasse pas, on y entre avec respect. Elle est l'un de ces nombreux bois sacrés qui, au Bénin comme ailleurs en Afrique de l'Ouest, ont servi de conservatoires naturels.\n\n### Ouidah 92 et les sculptures\nAu début des années 1990, lors du festival international des cultures vodun « Ouidah 92 », la forêt est aménagée pour accueillir les visiteurs. Des sculptures représentant les divinités du vodun et des scènes de l'histoire de la ville y sont installées par des artistes béninois. Elles font aujourd'hui partie du paysage de la forêt et aident à comprendre le panthéon vodun.",
    culture: "La forêt reste avant tout un lieu de culte. Les prêtres et adeptes du vodun y célèbrent des cérémonies, notamment en l'honneur de Loko, la divinité associée à l'iroko, l'arbre sacré. Certaines parties de la forêt ne sont pas accessibles aux visiteurs.\n\nElle illustre un lien fort entre spiritualité et nature : le vodun n'est pas seulement une religion de temples, c'est aussi un rapport au monde qui reconnaît une présence sacrée dans les arbres, les eaux et les animaux. Protéger la forêt, c'est respecter les ancêtres.\n\nPour les habitants de Ouidah, la forêt de Kpassè est aussi un lieu de mémoire de la ville, antérieur à l'arrivée du Danxomè et à la traite.",
    savoirs: "### Le savoir des plantes\nLes bois sacrés sont des réservoirs de plantes utilisées dans la pharmacopée traditionnelle. Les tradipraticiens connaissent leurs usages, les moments et les manières de les cueillir, et les règles qui encadrent leur utilisation.\n\n### Les règles du lieu\nInterdits de coupe, de chasse ou de certains comportements, tenues et attitudes attendues : ces règles, transmises oralement, sont un véritable système de gestion d'un espace naturel.\n\n### Lire les sculptures\nLes statues de la forêt représentent des divinités — Legba, gardien des passages ; Hevioso, divinité de la foudre ; Sakpata, liée à la terre ; Dan, le serpent… Un guide aide à reconnaître leurs attributs et leurs symboles.",
    communities: "Prêtres et dignitaires vodun de Ouidah, habitants du quartier, guides de la ville.",
    langues: "Fon, xwéla, français",
    personnalites: "Roi Kpassè, fondateur de Ouidah selon la tradition.",
    infos_pratiques: "Visite accompagnée d'un guide à l'entrée (contribution à prévoir). Respecter les interdits signalés et les zones fermées aux visiteurs, demander avant de photographier les autels. Se combine facilement avec le temple des Pythons et le musée d'histoire, tout proches.",
    chronologie: [
      ["XVIIe siècle", "Selon la tradition, le roi Kpassè fonde Ouidah, dans le royaume Xwéda."],
      ["1727", "Conquête de Ouidah par le Danxomè ; la forêt reste un lieu sacré de la ville."],
      ["Début des années 1990", "Aménagement pour le festival « Ouidah 92 » et installation de sculptures."],
      ["Aujourd'hui", "Lieu de culte vodun et site de visite parmi les plus fréquentés de Ouidah."]
    ],
    a_voir: [
      ["L'iroko du roi", "Le grand arbre associé au roi Kpassè, cœur de la forêt."],
      ["Les sculptures des divinités", "Legba, Hevioso, Sakpata, Dan… Un guide explique leurs symboles."],
      ["L'entrée et sa statue de Legba", "Gardien des passages, Legba accueille ceux qui entrent."]
    ],
    saviez_vous: ["Les bois sacrés comme celui de Kpassè comptent parmi les derniers îlots de forêt ancienne dans le sud du Bénin : le sacré y a joué le rôle d'une réserve naturelle.", "Loko, la divinité de l'iroko, est honorée dans de nombreux lieux du Bénin : les grands irokos sont souvent entourés d'offrandes et de pagnes."],
    sources: ["Direction du patrimoine culturel du Bénin", "Office du tourisme de Ouidah", "Festival international des cultures vodun « Ouidah 92 »"],
    recits: [
      { title: "Le roi devenu arbre", nature: "tradition_orale", body: "La tradition raconte que le roi Kpassè, poursuivi par ses ennemis, disparut dans la forêt et se transforma en un grand iroko pour leur échapper. L'arbre est depuis vénéré comme la présence du roi. Ce récit explique pourquoi on ne coupe pas les arbres de la forêt." }
    ],
    quiz: [
      { question: "Selon la tradition, en quoi le roi Kpassè s'est-il transformé ?", choices: ["En python", "En iroko", "En rivière"], answer: 1, explanation: "Le roi Kpassè se serait transformé en iroko, un grand arbre, pour échapper à ses ennemis." },
      { question: "Pourquoi la forêt de Kpassè a-t-elle été préservée au milieu de la ville ?", choices: ["C'est un parc national", "Elle est sacrée", "Elle est privée"], answer: 1, explanation: "Son caractère sacré l'a protégée : les interdits religieux jouent ici un rôle de conservation de la nature." },
      { question: "À quel royaume appartenait Ouidah avant la conquête du Danxomè ?", choices: ["Le royaume Xwéda (Houéda)", "Le royaume d'Oyo", "L'empire du Mali"], answer: 0, explanation: "Ouidah faisait partie du royaume Xwéda, dont la capitale était Savi, avant sa conquête en 1727." },
      { question: "Quelle divinité garde les passages et accueille les visiteurs à l'entrée ?", choices: ["Legba", "Hevioso", "Mami Wata"], answer: 0, explanation: "Legba est le gardien des passages et des carrefours ; sa statue se trouve souvent à l'entrée des lieux de culte." },
      { question: "Lors de quel événement des sculptures ont-elles été installées dans la forêt ?", choices: ["Le festival Ouidah 92", "L'indépendance de 1960", "La Coupe d'Afrique des nations"], answer: 0, explanation: "Les sculptures ont été installées au début des années 1990, à l'occasion du festival des cultures vodun « Ouidah 92 »." }
    ]
  },
  {
    id: 37,
    slug: "monument-amazones-cotonou",
    country: "Bénin",
    cat: "historique",
    name: "Esplanade et Monument des Amazones",
    region: "Littoral, Cotonou",
    featured: true,
    latitude: 6.3565,
    longitude: 2.4262,
    radius: 300,
    themes: ["resistances", "royaumes"],
    description: "Une statue monumentale d'une trentaine de mètres rend hommage aux Agojie, les guerrières du royaume du Danxomè, que les Européens ont appelées « Amazones ».",
    histoire: "Les Agojie (aussi appelées Minon, « nos mères ») formaient un corps militaire féminin du royaume du Danxomè, actif du XVIIIe à la fin du XIXe siècle. Elles combattirent notamment les troupes françaises lors des guerres de 1890 et 1892. Le monument, inauguré en 2022 sur l'esplanade qui porte leur nom, représente une guerrière debout, arme à la main.",
    culture: "Le monument est devenu un symbole de fierté et un lieu de rassemblement à Cotonou. Il invite à redécouvrir l'histoire des Agojie à partir des sources et des mémoires béninoises, au-delà des représentations coloniales et cinématographiques.",
    savoirs: "Transmission de l'histoire militaire et politique du Danxomè ; récits et chants liés aux Agojie conservés par les familles et les héraldistes.",
    communities: "Ville de Cotonou, historiens et associations mémorielles.",
    langues: "Fon, français",
    personnalites: "Les Agojie ; roi Ghézo (qui aurait renforcé le corps), roi Béhanzin.",
    infos_pratiques: "Accès libre, en plein air. Particulièrement animé en fin de journée.",
    sources: ["Présidence de la République du Bénin — inauguration du monument (2022)", "Maurice Ahanhanzo Glèlè, Le Danxomè, 1974"],
    recits: [],
    quiz: [
      { question: "Comment appelait-on les guerrières du Danxomè en fon ?", choices: ["Les Agojie (ou Minon)", "Les Kandakes", "Les Sofas"], answer: 0, explanation: "Les Agojie, ou Minon (« nos mères »). Les Kandakes étaient des reines de Koush ; les sofas, des soldats de l'armée de Samory Touré." },
      { question: "Quelle est la hauteur approximative de la statue ?", choices: ["5 mètres", "30 mètres", "100 mètres"], answer: 1, explanation: "La statue mesure une trentaine de mètres, ce qui en fait l'un des plus grands monuments du pays." }
    ]
  },
  {
    id: 101,
    slug: "porte-du-non-retour",
    country: "Bénin",
    cat: "memoire",
    name: "Porte du Non-Retour",
    region: "Atlantique, Ouidah (plage)",
    featured: true,
    latitude: 6.3244,
    longitude: 2.0892,
    radius: 300,
    themes: ["memoire-traite", "spiritualites"],
    description: "Sur la plage de Ouidah, face à l'océan, une grande arche marque le point final de la Route des Esclaves. La Porte du Non-Retour rend hommage aux millions d'Africaines et d'Africains arrachés à leur terre et déportés à travers l'Atlantique.\n\nC'est l'un des lieux de mémoire les plus forts du continent : un endroit où l'on vient comprendre, se recueillir, et où les descendants de la diaspora viennent renouer avec la terre de leurs ancêtres.",
    histoire: "### Ouidah, port de la traite\nDu XVIIe au XIXe siècle, Ouidah est l'un des principaux ports de la traite négrière sur la côte ouest-africaine. Les puissances européennes — Portugais, Français, Anglais, puis d'autres — y installent des forts et des comptoirs. Selon les estimations des historiens, près d'un million de captifs auraient été embarqués depuis Ouidah vers les Amériques, en particulier vers le Brésil et les Caraïbes.\n\n### De la ville à l'océan\nLes captifs, souvent issus de guerres et de razzias menées à l'intérieur des terres, étaient vendus sur la place des enchères, au cœur de la ville. Ils étaient ensuite conduits à pied jusqu'à la plage, à environ quatre kilomètres, le long de ce que l'on appelle aujourd'hui la Route des Esclaves. Comme il n'y avait pas de port, les navires restaient au large : les captifs étaient emmenés en pirogue à travers la barre, les puissants rouleaux de la côte, avant d'être entassés dans les cales.\n\n### Un monument pour la mémoire\nAu début des années 1990, le Bénin fait de Ouidah un lieu central de la mémoire de la traite. En 1994, l'UNESCO y lance le projet international « La Route de l'esclave », pour étudier cette histoire et en transmettre la mémoire. La Porte du Non-Retour est inaugurée en 1995. Ses bas-reliefs montrent des colonnes de captifs enchaînés marchant vers la mer.\n\n### Un lieu vivant\nLa Porte est aujourd'hui un lieu de visites scolaires, de cérémonies et de retrouvailles avec la diaspora. Chaque année, autour du 10 janvier, elle se trouve au cœur des célébrations du Vodun, qui rassemblent des milliers de personnes sur la plage. Illuminée la nuit, elle est devenue l'une des images emblématiques du Bénin.",
    culture: "Le nom de « Porte du Non-Retour » exprime la rupture définitive vécue par les déportés : pour la plupart, la plage de Ouidah fut la dernière image de l'Afrique.\n\nMais le lieu dit aussi le retour. Des descendants d'Africains déportés, venus du Brésil, des Caraïbes, des États-Unis ou d'ailleurs, viennent s'y recueillir, parfois lors de cérémonies de réconciliation avec la terre de leurs ancêtres. Ouidah garde d'ailleurs les traces de ces allers-retours : des familles afro-brésiliennes, les Agudas, s'y sont installées au XIXe siècle.\n\nLe lieu invite enfin à regarder cette histoire en face, du point de vue de celles et ceux qui l'ont subie, et à réfléchir à la responsabilité des différents acteurs de la traite, européens comme africains.",
    savoirs: "La mémoire de la traite se transmet à Ouidah de plusieurs manières : par les récits familiaux, par les cérémonies vodun qui honorent les ancêtres, par le travail des guides de la ville et par les recherches des historiens béninois.\n\nLes bas-reliefs de la Porte et les monuments de la Route des Esclaves ont été conçus comme des supports de transmission : ils racontent, par l'image, une histoire que les archives écrites ont longtemps présentée du seul point de vue des négriers.",
    communities: "Ville de Ouidah, guides de la Route des Esclaves, dignitaires vodun, associations mémorielles, descendants de la diaspora.",
    langues: "Fon, xwéla, français, anglais, portugais",
    personnalites: "—",
    infos_pratiques: "Accès libre, sur la plage, à environ 4 km du centre de Ouidah. Idéalement, arriver à pied ou à vélo par la Route des Esclaves, avec un guide. Le lieu est beau de jour comme de nuit, lorsqu'il est illuminé. C'est un lieu de recueillement : adopter une attitude respectueuse, notamment lors des cérémonies. Baignade dangereuse (forts courants).",
    chronologie: [
      ["XVIIe siècle", "Les Européens installent des comptoirs à Ouidah, alors capitale du royaume Xwéda."],
      ["1721", "Construction du fort portugais São João Baptista de Ajudá."],
      ["1727", "Le Danxomè conquiert Ouidah, qui devient son port."],
      ["XVIIIe - XIXe siècles", "Ouidah est l'un des principaux ports de la traite atlantique."],
      ["Milieu du XIXe siècle", "Fin progressive de la traite atlantique ; retour de familles afro-brésiliennes (Agudas)."],
      ["1994", "L'UNESCO lance à Ouidah le projet « La Route de l'esclave »."],
      ["1995", "Inauguration de la Porte du Non-Retour."],
      ["Chaque 10 janvier", "Célébrations du Vodun sur la plage, près de la Porte."]
    ],
    a_voir: [
      ["Les bas-reliefs de l'arche", "De près, observer les colonnes de captifs enchaînés : une œuvre à regarder lentement."],
      ["La plage", "Imaginer les pirogues franchissant la barre vers les navires restés au large."],
      ["La Route des Esclaves", "Les 4 km qui mènent du centre de Ouidah à la plage, jalonnés de monuments."],
      ["La Porte illuminée", "À la nuit tombée, l'arche éclairée offre une atmosphère de recueillement particulière."]
    ],
    saviez_vous: ["Ouidah n'avait pas de port : les navires négriers restaient au large, et les captifs étaient conduits jusqu'à eux en pirogue, à travers les rouleaux de la barre.", "C'est à Ouidah, en 1994, que l'UNESCO a lancé le projet international « La Route de l'esclave », devenu depuis « Routes des personnes mises en esclavage »."],
    sources: ["UNESCO — Projet « La Route de l'esclave » (lancé à Ouidah en 1994)", "Musée d'histoire de Ouidah", "Base de données Slave Voyages (estimations des départs depuis Ouidah)"],
    recits: [
      { title: "La dernière vue de la terre natale", nature: "recit_communautaire", body: "À Ouidah, on dit que la plage fut pour beaucoup la dernière image de l'Afrique. Le nom de « Porte du Non-Retour » exprime cette rupture. Mais les cérémonies qui s'y tiennent aujourd'hui, en présence de descendants venus d'outre-Atlantique, en ont aussi fait un lieu de retour symbolique et de réconciliation avec l'histoire." }
    ],
    quiz: [
      { question: "Quel projet l'UNESCO a-t-il lancé à Ouidah en 1994 ?", choices: ["La Route de la soie", "La Route de l'esclave", "Les Villes créatives"], answer: 1, explanation: "Le projet « La Route de l'esclave » a été lancé à Ouidah en 1994 pour étudier et transmettre l'histoire de la traite." },
      { question: "En quelle année la Porte du Non-Retour a-t-elle été inaugurée ?", choices: ["1895", "1960", "1995"], answer: 2, explanation: "Le monument a été inauguré en 1995, un an après le lancement du projet de l'UNESCO." },
      { question: "Pourquoi les captifs étaient-ils conduits en pirogue jusqu'aux navires ?", choices: ["Ouidah n'avait pas de port", "Les navires étaient trop grands pour la lagune", "C'était une tradition religieuse"], answer: 0, explanation: "Sans port, les navires restaient au large ; les pirogues franchissaient la barre pour les atteindre." },
      { question: "Environ combien de captifs auraient été embarqués depuis Ouidah, selon les historiens ?", choices: ["Quelques milliers", "Près d'un million", "Plus de dix millions"], answer: 1, explanation: "Les estimations des historiens avancent près d'un million de personnes déportées depuis Ouidah." },
      { question: "Qui sont les Agudas ?", choices: ["Des familles afro-brésiliennes installées sur la côte", "Des gardiens de la Porte", "Des rois de Ouidah"], answer: 0, explanation: "Les Agudas descendent d'Africains revenus du Brésil au XIXe siècle ; ils ont marqué Ouidah et la côte." }
    ]
  },
  {
    id: 102,
    slug: "route-des-esclaves-ouidah",
    country: "Bénin",
    cat: "memoire",
    name: "Route des Esclaves de Ouidah",
    region: "Atlantique, Ouidah",
    featured: true,
    latitude: 6.344,
    longitude: 2.0875,
    radius: 2500,
    themes: ["memoire-traite", "spiritualites"],
    description: "Une piste d'environ quatre kilomètres relie le centre de Ouidah à l'océan. C'est la Route des Esclaves : le chemin que des centaines de milliers de captifs ont été forcés de parcourir, de la place des enchères jusqu'aux navires.\n\nJalonnée de monuments, d'arbres symboliques et de sculptures, elle se parcourt aujourd'hui à pied, étape par étape, comme un chemin de mémoire. C'est l'un des parcours les plus émouvants d'Afrique de l'Ouest.",
    histoire: "### Un parcours de la traite\nAux XVIIIe et XIXe siècles, Ouidah est le principal port du royaume du Danxomè et l'un des grands ports de la traite atlantique. Les captifs, souvent faits prisonniers lors de guerres et de razzias à l'intérieur des terres, sont amenés en ville, vendus, puis conduits vers la plage pour être embarqués.\n\n### Les étapes\nLe parcours commence sur l'ancienne place des enchères, aujourd'hui place Chacha, du nom de Francisco Félix de Souza, négrier d'origine brésilienne devenu l'un des hommes les plus puissants de Ouidah au XIXe siècle. Il passe par l'Arbre de l'Oubli, puis par la case Zomaï, où les captifs étaient enfermés dans l'obscurité en attendant le départ. Plus loin, le mémorial de Zoungbodji rappelle ceux qui mouraient en chemin et étaient enterrés dans une fosse commune. L'Arbre du Retour précède enfin l'arrivée sur la plage, où se dresse la Porte du Non-Retour.\n\n### Un chemin de mémoire\nAu début des années 1990, le Bénin et l'UNESCO font de Ouidah un lieu central de la mémoire de la traite. Le projet « La Route de l'esclave », lancé à Ouidah en 1994, s'accompagne de l'aménagement du parcours : monuments, sculptures et panneaux explicatifs sont installés, souvent œuvres d'artistes béninois. Des travaux récents ont rénové la route et ses abords.",
    culture: "Parcourir la Route des Esclaves, c'est mettre ses pas dans ceux des déportés. Les guides de Ouidah y racontent l'histoire, mais aussi les traditions orales liées à chaque étape.\n\nLa route pose aussi des questions difficiles : celle du rôle des négriers européens et brésiliens, mais également celle de la participation de royaumes africains à ce commerce. Ouidah en fait un lieu de réflexion, de recueillement et de réconciliation, notamment avec les descendants de la diaspora qui viennent y marcher.",
    savoirs: "### La mémoire orale\nLes récits de l'Arbre de l'Oubli et de l'Arbre du Retour, transmis oralement, disent la violence de l'arrachement mais aussi la croyance dans le retour des âmes. Ils sont une clé pour comprendre comment les populations ont pensé et raconté la traite.\n\n### Les monuments\nLes sculptures et monuments du parcours, souvent réalisés par des artistes béninois, utilisent les symboles du vodun et de la culture fon pour raconter l'histoire : ils sont une forme de transmission par l'image.",
    communities: "Guides de Ouidah, familles de la ville, dignitaires vodun, associations mémorielles.",
    langues: "Fon, français",
    personnalites: "Francisco Félix de Souza, dit « Chacha », négrier installé à Ouidah au XIXe siècle, allié du roi Ghézo (la place porte son nom).",
    infos_pratiques: "Parcours de 4 km, à faire à pied, à vélo ou en taxi-moto, idéalement avec un guide pour comprendre chaque étape. Prévoir 2 à 3 heures, de l'eau et une protection contre le soleil ; éviter les heures les plus chaudes. Finir à la Porte du Non-Retour, sur la plage.",
    chronologie: [
      ["1727", "Ouidah passe sous le contrôle du Danxomè et devient son port de traite."],
      ["XVIIIe - XIXe siècles", "Des centaines de milliers de captifs empruntent le chemin vers la plage."],
      ["1818", "Francisco Félix de Souza aide Ghézo à prendre le pouvoir et devient le « Chacha » de Ouidah."],
      ["1994", "Lancement à Ouidah du projet de l'UNESCO « La Route de l'esclave »."],
      ["1995", "Inauguration de la Porte du Non-Retour, au bout de la route."]
    ],
    a_voir: [
      ["La place Chacha", "L'ancienne place des enchères, point de départ du parcours."],
      ["L'Arbre de l'Oubli", "Lieu de l'un des rituels les plus marquants de la tradition orale."],
      ["La case Zomaï", "L'emplacement où les captifs étaient enfermés dans l'obscurité avant le départ."],
      ["Le mémorial de Zoungbodji", "Hommage à ceux qui moururent avant l'embarquement."],
      ["L'Arbre du Retour", "Dernière étape avant la plage, symbole de l'espoir du retour des âmes."]
    ],
    saviez_vous: ["« Zomaï » signifierait « là où la lumière ne pénètre pas » : les captifs y étaient enfermés dans le noir pour les désorienter avant le voyage.", "Le titre de « Chacha » donné à Francisco Félix de Souza est resté dans sa famille, dont les descendants vivent toujours à Ouidah."],
    sources: ["UNESCO — Projet « La Route de l'esclave »", "Musée d'histoire de Ouidah", "Office du tourisme de Ouidah"],
    recits: [
      { title: "L'Arbre de l'Oubli et l'Arbre du Retour", nature: "tradition_orale", body: "Selon la tradition, les captifs devaient tourner autour de l'Arbre de l'Oubli — neuf fois pour les hommes, sept fois pour les femmes — afin d'oublier leur nom, leur famille et leur terre. Plus loin, on les faisait tourner trois fois autour de l'Arbre du Retour, pour que leur âme revienne un jour au pays de leurs ancêtres. Ces gestes disent la violence de l'arrachement, mais aussi l'espoir d'un retour." }
    ],
    quiz: [
      { question: "Combien de fois, selon la tradition, les hommes devaient-ils tourner autour de l'Arbre de l'Oubli ?", choices: ["3 fois", "7 fois", "9 fois"], answer: 2, explanation: "Neuf fois pour les hommes, sept fois pour les femmes, selon la tradition rapportée à Ouidah." },
      { question: "Quelle est la longueur approximative de la Route des Esclaves ?", choices: ["400 mètres", "4 kilomètres", "40 kilomètres"], answer: 1, explanation: "La route relie le centre de Ouidah à la plage sur environ 4 km." },
      { question: "Que rappelle le mémorial de Zoungbodji ?", choices: ["Une victoire militaire", "Une fosse commune de captifs morts en chemin", "La fondation de la ville"], answer: 1, explanation: "Zoungbodji rappelle les captifs morts avant l'embarquement, enterrés dans une fosse commune." },
      { question: "Où commence la Route des Esclaves ?", choices: ["À la place Chacha, ancienne place des enchères", "Au palais d'Abomey", "Au port de Cotonou"], answer: 0, explanation: "Le parcours part de l'ancienne place des enchères, aujourd'hui place Chacha, au centre de Ouidah." },
      { question: "Que signifierait « Zomaï », le nom de la case où les captifs étaient enfermés ?", choices: ["La maison du roi", "Là où la lumière ne pénètre pas", "Le chemin de la mer"], answer: 1, explanation: "Les captifs y étaient enfermés dans l'obscurité, « là où la lumière ne pénètre pas »." }
    ]
  },
  {
    id: 103,
    slug: "fort-portugais-ouidah",
    country: "Bénin",
    cat: "historique",
    name: "Fort portugais — Musée d'histoire de Ouidah",
    region: "Atlantique, Ouidah",
    featured: false,
    latitude: 6.361,
    longitude: 2.088,
    radius: 250,
    themes: ["memoire-traite", "architecture", "resistances"],
    description: "Au centre de Ouidah, derrière des murs blancs, l'ancien fort portugais São João Baptista de Ajudá abrite le Musée d'histoire de Ouidah. On y découvre l'histoire de la ville, de la traite atlantique et des liens profonds qui unissent le Bénin au Brésil.\n\nC'est souvent la première étape conseillée d'une visite de Ouidah : pour comprendre le contexte avant de parcourir la Route des Esclaves.",
    histoire: "### Les forts européens de Ouidah\nAu XVIIIe siècle, plusieurs puissances européennes possèdent des forts à Ouidah, alors principal port du commerce avec l'intérieur du pays. Les Français, les Anglais et les Portugais y ont chacun leur établissement. Ces forts servent de comptoirs : on y stocke les marchandises et l'on y organise la traite.\n\n### Le fort São João Baptista de Ajudá\nLe fort portugais est construit en 1721. « Ajudá » est le nom portugais de Ouidah. Il reste lié au commerce avec le Brésil, et en particulier avec Salvador de Bahia, d'où venaient le tabac et l'eau-de-vie échangés contre des captifs.\n\n### Une enclave jusqu'en 1961\nFait étonnant, le Portugal conserve le fort bien après la fin de la traite et même après l'indépendance du Dahomey en 1960 : c'est alors une minuscule enclave portugaise en territoire dahoméen. En 1961, le gouvernement dahoméen en reprend possession ; les derniers occupants portugais y mettent le feu avant de partir.\n\n### Le musée\nRestauré, le fort accueille depuis 1967 le Musée d'histoire de Ouidah. Il présente l'histoire du royaume Xwéda, de la conquête par le Danxomè, de la traite, des cultes vodun et des échanges culturels entre les deux rives de l'Atlantique.",
    culture: "Le musée met en lumière une histoire souvent méconnue : celle des Agudas, Africains et descendants d'Africains revenus du Brésil au XIXe siècle, après l'abolition de l'esclavage ou après avoir racheté leur liberté. Installés sur la côte du Bénin, du Togo et du Nigéria, ils ont apporté une architecture, une cuisine, des fêtes et des noms de famille portugais que l'on retrouve encore aujourd'hui (de Souza, da Silva, d'Almeida…).\n\nLe musée montre aussi comment les cultes vodun ont traversé l'Atlantique : ils ont nourri le candomblé au Brésil, le vaudou en Haïti ou la santería à Cuba. Ouidah est ainsi un point de départ d'une culture afro-atlantique.",
    savoirs: "### Architecture\nLe fort témoigne de l'architecture coloniale portugaise adaptée au climat : murs épais, cour intérieure, bâtiments bas. En ville, les maisons afro-brésiliennes des Agudas, à étage et aux façades décorées, en sont une autre facette.\n\n### Les collections\nCartes anciennes, objets de traite, documents, objets de culte et photographies permettent de comprendre les circuits du commerce atlantique et leurs conséquences.",
    communities: "Musée d'histoire de Ouidah, communauté aguda de Ouidah, historiens béninois.",
    langues: "Fon, français, portugais",
    personnalites: "—",
    infos_pratiques: "Musée ouvert au public, avec visites guidées (horaires et tarifs à confirmer sur place). Prévoir environ 1 heure. Idéal en début de visite de Ouidah, avant la Route des Esclaves.",
    chronologie: [
      ["1721", "Construction du fort portugais São João Baptista de Ajudá."],
      ["1727", "Conquête de Ouidah par le Danxomè ; les forts européens restent en place."],
      ["XIXe siècle", "Retour de familles afro-brésiliennes, les Agudas, sur la côte."],
      ["1960", "Indépendance du Dahomey ; le fort reste portugais."],
      ["1961", "Le Dahomey reprend possession du fort ; ses occupants y mettent le feu."],
      ["1967", "Ouverture du Musée d'histoire de Ouidah dans le fort restauré."]
    ],
    a_voir: [
      ["Les salles du musée", "L'histoire de Ouidah, de la traite et des liens avec le Brésil."],
      ["La chapelle", "Petit édifice blanc de l'ancien fort, dans la cour."],
      ["La résidence du gouverneur", "L'ancien logement du représentant portugais."],
      ["Les maisons afro-brésiliennes", "En ville, les façades décorées des familles agudas."]
    ],
    saviez_vous: ["Pendant un an après l'indépendance du Dahomey, le fort de Ouidah est resté une minuscule enclave portugaise, l'une des plus petites « colonies » du monde.", "Des noms de famille comme de Souza, da Silva ou d'Almeida, courants sur la côte béninoise, rappellent l'histoire des Agudas revenus du Brésil."],
    sources: ["Musée d'histoire de Ouidah", "Direction du patrimoine culturel du Bénin"],
    recits: [],
    quiz: [
      { question: "En quelle année le fort portugais de Ouidah a-t-il été construit ?", choices: ["1492", "1721", "1894"], answer: 1, explanation: "Le fort São João Baptista de Ajudá a été construit en 1721." },
      { question: "Qui sont les « Agudas » ?", choices: ["Des descendants d'Africains revenus du Brésil", "Des soldats portugais", "Une dynastie royale d'Abomey"], answer: 0, explanation: "Les Agudas descendent d'Africains revenus du Brésil au XIXe siècle ; ils ont marqué la culture de la côte." },
      { question: "En quelle année le Dahomey a-t-il repris possession du fort ?", choices: ["1894", "1961", "1990"], answer: 1, explanation: "Le fort est resté portugais jusqu'en 1961, un an après l'indépendance du Dahomey." },
      { question: "Que signifie « Ajudá » en portugais ?", choices: ["Ouidah", "Aide", "Forteresse"], answer: 0, explanation: "Ajudá est le nom portugais de la ville de Ouidah." },
      { question: "Quel pays d'Amérique est particulièrement lié à Ouidah par l'histoire de la traite et des retours ?", choices: ["Le Brésil", "Le Canada", "Le Chili"], answer: 0, explanation: "Ouidah entretenait des liens étroits avec le Brésil, notamment Salvador de Bahia ; des Afro-Brésiliens y sont revenus au XIXe siècle." }
    ]
  },
  {
    id: 104,
    slug: "temple-des-pythons-ouidah",
    country: "Bénin",
    cat: "culturel",
    name: "Temple des Pythons",
    region: "Atlantique, Ouidah",
    featured: false,
    latitude: 6.3651,
    longitude: 2.0859,
    radius: 200,
    themes: ["spiritualites", "faune-flore"],
    description: "Au cœur de Ouidah, un petit temple abrite des dizaines de pythons royaux, libres et respectés : c'est le temple de Dangbé, divinité protectrice de la ville. Juste en face se dresse la basilique de l'Immaculée-Conception.\n\nCe face-à-face résume Ouidah : une ville où le vodun et le christianisme se côtoient, et où les pythons sont traités comme des êtres sacrés.",
    histoire: "### Le culte de Dangbé\nLe culte du python remonte au royaume Xwéda, avant la conquête de Ouidah par le Danxomè en 1727. Le python royal y était honoré comme une divinité protectrice. La tradition raconte qu'un python aurait sauvé le roi et son armée lors d'une guerre, ce qui lui valut d'être vénéré.\n\n### Un culte qui survit aux conquêtes\nAprès la conquête, le Danxomè ne supprime pas le culte : il l'intègre, comme il le fait souvent avec les divinités des peuples conquis. Dangbé reste l'une des grandes divinités de Ouidah.\n\n### Le temple et la basilique\nLe temple actuel se trouve sur une place du centre-ville. En face, la basilique de l'Immaculée-Conception, construite au début du XXe siècle, témoigne de la présence de l'Église catholique. Cette proximité est souvent citée comme un symbole de la coexistence religieuse au Bénin.",
    culture: "À Ouidah, le python royal est respecté : on ne le tue pas. Autrefois, tuer un python pouvait être puni très sévèrement. S'il entre dans une maison, on prévient les prêtres du temple, qui viennent le récupérer.\n\nLe temple est aussi un lieu d'initiation et de cérémonies pour les adeptes de Dangbé. Pour les visiteurs, il est l'occasion de comprendre que le vodun n'est pas « de la magie » comme on le présente souvent, mais une religion à part entière, avec ses divinités, ses prêtres, ses règles et ses fêtes.",
    savoirs: "### Le python royal\nLe python royal (Python regius) est un serpent non venimeux, calme, qui se roule en boule lorsqu'il est inquiet. Les gardiens du temple savent le manipuler et le soigner.\n\n### Les rites\nLes prêtres de Dangbé connaissent les chants, les offrandes et les interdits liés à la divinité. Ce savoir se transmet dans le cadre de l'initiation.",
    communities: "Prêtres et adeptes de Dangbé, habitants de Ouidah.",
    langues: "Fon, xwéla, français",
    personnalites: "—",
    infos_pratiques: "Visite guidée sur place (contribution à prévoir). Les guides proposent parfois de porter un python autour du cou : c'est facultatif. Se combine avec la basilique d'en face, la forêt de Kpassè et le musée d'histoire.",
    chronologie: [
      ["Avant 1727", "Le culte de Dangbé est déjà bien établi dans le royaume Xwéda."],
      ["1727", "Conquête de Ouidah par le Danxomè, qui maintient le culte."],
      ["Début du XXe siècle", "Construction de la basilique de l'Immaculée-Conception, face au temple."],
      ["Aujourd'hui", "Le temple est l'un des lieux les plus visités de Ouidah."]
    ],
    a_voir: [
      ["La case des pythons", "Des dizaines de pythons royaux y vivent librement."],
      ["L'arbre sacré de la cour", "Au cœur de l'enclos, un arbre ancien entouré d'offrandes."],
      ["La basilique en face", "Pour saisir le face-à-face entre vodun et christianisme."]
    ],
    saviez_vous: ["Le python royal se roule en boule quand il a peur, d'où son surnom de « python boule ».", "On dit à Ouidah que les pythons sortent parfois la nuit se promener en ville, et que les habitants les ramènent au temple."],
    sources: ["Office du tourisme de Ouidah", "Direction du patrimoine culturel du Bénin"],
    recits: [
      { title: "Le python qui sauva le roi", nature: "tradition_orale", body: "On raconte qu'au temps du royaume Xwéda, un python surgit pour protéger le roi et ses hommes, ou pour les guider vers la victoire selon d'autres versions. Depuis, le python royal est honoré comme Dangbé, et le tuer est un interdit grave." }
    ],
    quiz: [
      { question: "Quelle divinité est honorée au temple des Pythons ?", choices: ["Dangbé", "Shango", "Mami Wata"], answer: 0, explanation: "Dangbé est la divinité représentée par le python royal, protecteur de Ouidah." },
      { question: "Quel édifice fait face au temple des Pythons ?", choices: ["Le fort portugais", "La basilique de l'Immaculée-Conception", "Le palais royal"], answer: 1, explanation: "Le temple et la basilique se font face, symbole de la coexistence religieuse à Ouidah." },
      { question: "Le python royal est-il venimeux ?", choices: ["Oui, très", "Non", "Seulement la nuit"], answer: 1, explanation: "Le python royal n'est pas venimeux ; il est calme et se roule en boule lorsqu'il a peur." },
      { question: "Que font les habitants si un python entre dans leur maison ?", choices: ["Ils le tuent", "Ils préviennent les prêtres du temple", "Ils le relâchent en forêt"], answer: 1, explanation: "Les prêtres du temple viennent récupérer le python : le tuer est un interdit grave." },
      { question: "De quel royaume vient le culte de Dangbé ?", choices: ["Le royaume Xwéda", "L'empire du Ghana", "Le royaume du Kongo"], answer: 0, explanation: "Le culte de Dangbé remonte au royaume Xwéda, avant la conquête du Danxomè." }
    ]
  },
  {
    id: 105,
    slug: "fete-du-vodun-ouidah",
    country: "Bénin",
    cat: "culturel",
    name: "Fête du Vodun de Ouidah",
    region: "Atlantique, Ouidah (plage)",
    featured: true,
    latitude: 6.325,
    longitude: 2.088,
    radius: 1500,
    themes: ["festivals", "spiritualites", "musiques-danses"],
    description: "Chaque année, autour du 10 janvier, Ouidah devient la capitale mondiale du vodun. Sur la plage, près de la Porte du Non-Retour, des milliers de personnes se rassemblent : dignitaires en tenue d'apparat, adeptes, familles, visiteurs du monde entier et descendants de la diaspora.\n\nTambours, chants, danses et sorties de masques rythment la fête nationale des religions endogènes, devenue aussi l'un des plus grands événements culturels d'Afrique de l'Ouest.",
    histoire: "### Une religion longtemps dénigrée\nLe vodun est un ensemble de croyances et de pratiques né dans l'aire culturelle adja-fon, entre l'actuel Togo, le Bénin et le Nigéria. Il reconnaît un Dieu suprême et une multitude de divinités (les vodun) liées aux forces de la nature, aux ancêtres et à la vie sociale. Pendant la période coloniale, il a été combattu et caricaturé, souvent réduit à de la « sorcellerie ».\n\n### La reconnaissance\nAprès des années de répression, notamment sous le régime révolutionnaire des années 1970-1980, le Bénin reconnaît officiellement la place du vodun. Le festival « Ouidah 92 », au début des années 1990, marque un tournant. Le 10 janvier devient la journée nationale des religions endogènes, jour férié célébré chaque année depuis la fin des années 1990.\n\n### Les Vodun Days\nDepuis 2024, l'État béninois organise les « Vodun Days » : plusieurs jours de célébrations, de spectacles et de rencontres autour du 10 janvier à Ouidah, pour faire connaître le vodun et attirer visiteurs et descendants de la diaspora.",
    culture: "La fête rassemble les grandes figures du vodun, comme le Daagbo Hounon, dignitaire de premier rang à Ouidah, les prêtres et adeptes des différentes divinités, et un public immense.\n\nOn y voit les Zangbéto, gardiens de la nuit couverts de raphia, qui tournoient sans que l'on sache qui se cache dessous ; les Egungun, qui incarnent les ancêtres revenus parmi les vivants, drapés de tissus somptueux ; et de nombreux groupes de musique et de danse.\n\nPour beaucoup de Béninois, c'est une fête de fierté : celle d'une spiritualité africaine reconnue et célébrée. Pour les descendants d'Africains déportés, c'est aussi l'occasion de retrouver des racines dont le candomblé brésilien, le vaudou haïtien ou la santería cubaine sont les héritiers.",
    savoirs: "### Les rythmes et les danses\nChaque divinité a ses rythmes, ses chants et ses pas de danse. Les tambourinaires et les chanteurs sont les dépositaires de ce répertoire, appris de longues années.\n\n### Les masques et costumes\nLa confection des costumes de Zangbéto (raphia) et d'Egungun (tissus, broderies, perles) relève de savoir-faire spécialisés, souvent tenus secrets.\n\n### Les divinités\nLegba (gardien des passages), Hevioso (foudre), Sakpata (terre), Dan (serpent arc-en-ciel), Mami Wata (eaux)… Chaque vodun a ses couleurs, ses interdits et ses adeptes.",
    communities: "Dignitaires et adeptes du vodun, collectivités familiales, ville de Ouidah, ministère du Tourisme et de la Culture.",
    langues: "Fon, yoruba, français",
    personnalites: "Le Daagbo Hounon, dignitaire vodun de premier rang à Ouidah.",
    infos_pratiques: "Chaque année autour du 10 janvier (programme des Vodun Days à consulter à l'avance). Forte affluence : réserver l'hébergement tôt et prévoir un transport. Certaines cérémonies ne se photographient pas : demander et respecter les consignes des organisateurs et des dignitaires.",
    chronologie: [
      ["Époque coloniale", "Le vodun est combattu et caricaturé par l'administration et les missions."],
      ["Années 1970-1980", "Les pratiques vodun sont encore réprimées sous le régime révolutionnaire."],
      ["Début des années 1990", "Festival international des cultures vodun « Ouidah 92 »."],
      ["Fin des années 1990", "Le 10 janvier devient journée nationale des religions endogènes."],
      ["2024", "Première édition des « Vodun Days » à Ouidah."]
    ],
    a_voir: [
      ["Les Zangbéto", "Les gardiens de la nuit, grands masques de raphia qui tournoient."],
      ["Les Egungun", "Les revenants, drapés de tissus brodés, incarnant les ancêtres."],
      ["La cérémonie sur la plage", "Autour de la Porte du Non-Retour, le cœur des célébrations."]
    ],
    saviez_vous: ["Le Bénin est l'un des rares pays au monde à avoir fait d'une fête des religions traditionnelles un jour férié national.", "Le mot « vodun » désigne à la fois la religion et chacune de ses divinités : on parle des vodun au pluriel."],
    sources: ["Gouvernement du Bénin — Vodun Days", "Office du tourisme de Ouidah", "Festival international des cultures vodun « Ouidah 92 »"],
    recits: [
      { title: "Qui se cache sous le Zangbéto ?", nature: "tradition_orale", body: "On dit que personne ne se cache sous le Zangbéto : ce sont des esprits qui l'animent. Pour prouver qu'il est vide, ses gardiens le soulèvent parfois devant la foule. Gardiens de la nuit, les Zangbéto veillaient autrefois sur la sécurité des villages et faisaient respecter l'ordre." }
    ],
    quiz: [
      { question: "Quelle est la date de la fête nationale du Vodun au Bénin ?", choices: ["1er août", "10 janvier", "25 décembre"], answer: 1, explanation: "Le 10 janvier est la journée nationale des religions endogènes au Bénin." },
      { question: "Quel est le rôle traditionnel des Zangbéto ?", choices: ["Gardiens de la nuit", "Musiciens de cour", "Chasseurs"], answer: 0, explanation: "Les Zangbéto sont les gardiens de la nuit, chargés de veiller sur la communauté." },
      { question: "Que représentent les Egungun ?", choices: ["Les ancêtres revenus parmi les vivants", "Les rois d'Abomey", "Les esprits de la forêt"], answer: 0, explanation: "Les Egungun incarnent les ancêtres qui reviennent visiter les vivants." },
      { question: "Depuis quelle année l'État organise-t-il les « Vodun Days » ?", choices: ["1960", "1998", "2024"], answer: 2, explanation: "Les Vodun Days, plusieurs jours de célébrations autour du 10 janvier, existent depuis 2024." },
      { question: "Quel culte brésilien est un héritier des religions vodun et yoruba ?", choices: ["Le candomblé", "Le carnaval", "La capoeira"], answer: 0, explanation: "Le candomblé, pratiqué notamment à Bahia, est né des religions emportées par les déportés d'Afrique de l'Ouest." }
    ]
  },
  {
    id: 106,
    slug: "parc-national-pendjari",
    country: "Bénin",
    cat: "naturel",
    name: "Parc national de la Pendjari",
    region: "Atacora, Tanguiéta",
    featured: true,
    latitude: 11.25,
    longitude: 1.55,
    radius: 40000,
    themes: ["faune-flore", "eaux"],
    description: "Dans le nord-ouest du Bénin, la Pendjari est l'un des derniers grands refuges de la faune sauvage en Afrique de l'Ouest : lions, éléphants, buffles, hippopotames et antilopes.",
    histoire: "La Pendjari fait partie du complexe transfrontalier W-Arly-Pendjari (WAP), partagé entre le Bénin, le Burkina Faso et le Niger, inscrit au patrimoine mondial de l'UNESCO en 2017. Depuis 2017, le parc est géré par l'État béninois en partenariat avec l'organisation African Parks.",
    culture: "Les communautés riveraines, notamment waaba, berba et gourmantché, ont des liens anciens avec ces terres. La gestion du parc cherche à concilier conservation et vie des villages voisins.",
    savoirs: "Connaissance de la faune et des plantes par les communautés riveraines ; savoirs des pisteurs et écogardes.",
    communities: "Villages riverains de la Pendjari, écogardes, African Parks.",
    langues: "Waama, berba, gourmantché, bariba, français",
    personnalites: "—",
    infos_pratiques: "Visite uniquement dans le cadre prévu par la direction du parc (entrées, guides et règles de sécurité à vérifier avant le départ). Saison sèche (décembre à mai) plus favorable à l'observation des animaux.",
    sources: ["UNESCO — Complexe W-Arly-Pendjari (extension 2017)", "African Parks — Parc national de la Pendjari"],
    recits: [],
    quiz: [
      { question: "Avec quels pays le Bénin partage-t-il le complexe W-Arly-Pendjari ?", choices: ["Togo et Ghana", "Burkina Faso et Niger", "Nigéria et Cameroun"], answer: 1, explanation: "Le complexe WAP s'étend sur le Bénin, le Burkina Faso et le Niger." },
      { question: "Quel grand félin trouve à la Pendjari l'un de ses derniers refuges en Afrique de l'Ouest ?", choices: ["Le lion", "Le tigre", "Le jaguar"], answer: 0, explanation: "Le lion d'Afrique de l'Ouest est menacé ; le complexe WAP abrite l'essentiel de sa population." },
      { question: "Comment se comporter lors d'un safari responsable ?", choices: ["Nourrir les animaux pour les attirer", "Rester dans le véhicule et garder ses distances", "Sortir du véhicule pour de meilleures photos"], answer: 1, explanation: "On reste dans le véhicule, à distance, sans nourrir les animaux : c'est leur sécurité et la vôtre." }
    ]
  },
  {
    id: 107,
    slug: "tata-somba-boukoumbe",
    country: "Bénin",
    cat: "savoirs",
    name: "Tata somba de Boukoumbé",
    region: "Atacora, Boukoumbé",
    featured: false,
    latitude: 10.18,
    longitude: 1.11,
    radius: 5000,
    themes: ["architecture", "artisanat", "langues"],
    description: "Dans la région de Boukoumbé, les Otammari (Batammariba) construisent les « takienta » ou tata somba : de petites maisons-forteresses en terre à étage, véritables chefs-d'œuvre d'architecture.",
    histoire: "Ce type d'habitat s'est développé dans les montagnes de l'Atacora, de part et d'autre de la frontière entre le Bénin et le Togo. Côté togolais, le paysage du Koutammakou, pays des Batammariba, est inscrit au patrimoine mondial de l'UNESCO depuis 2004.",
    culture: "Chaque takienta abrite une famille. Le rez-de-chaussée accueille les animaux et la cuisine ; l'étage, en terrasse, sert à sécher les récoltes et porte des greniers coiffés de chaume. L'habitat traduit une vision du monde : la maison est aussi un être vivant, liée aux ancêtres.",
    savoirs: "Construction en terre crue modelée à la main, crépissage, charpentes en bois et toitures de paille ; transmission des techniques entre générations.",
    communities: "Communautés otammari de Boukoumbé et des villages voisins.",
    langues: "Ditammari, français",
    personnalites: "—",
    infos_pratiques: "Visite de tata avec un guide local et l'accord des familles qui y vivent. Une contribution est souvent demandée : se renseigner auprès du guide.",
    sources: ["UNESCO — Koutammakou, le pays des Batammariba (Togo, 2004)", "Direction du patrimoine culturel du Bénin"],
    recits: [],
    quiz: [
      { question: "Quel peuple construit les takienta (tata somba) ?", choices: ["Les Otammari", "Les Toffinu", "Les Yoruba"], answer: 0, explanation: "Les Otammari (Batammariba) de l'Atacora construisent ces maisons-forteresses." },
      { question: "À quoi sert la terrasse à l'étage d'une takienta ?", choices: ["À sécher les récoltes et abriter les greniers", "À élever des chevaux", "À recevoir les marchés"], answer: 0, explanation: "L'étage en terrasse sert au séchage des récoltes et porte les greniers." }
    ]
  },
  {
    id: 108,
    slug: "musee-honme-porto-novo",
    country: "Bénin",
    cat: "historique",
    name: "Palais royal Honmè — Porto-Novo",
    region: "Ouémé, Porto-Novo",
    featured: false,
    latitude: 6.4975,
    longitude: 2.615,
    radius: 300,
    themes: ["royaumes", "architecture"],
    description: "Ancien palais des rois de Porto-Novo, le palais Honmè est aujourd'hui un musée qui fait découvrir l'organisation de la cour et la vie du royaume.",
    histoire: "Porto-Novo, aussi appelée Hogbonou ou Adjatchè, fut la capitale d'un royaume fondé par des princes venus d'Allada. Au XIXe siècle, le roi Toffa y régnait ; il signa avec la France un traité de protectorat. Porto-Novo est aujourd'hui la capitale politique du Bénin. Le mot « Honmè » signifie « à l'intérieur du palais ».",
    culture: "La visite fait découvrir les appartements royaux, les espaces des épouses, les cours de cérémonie et les objets de la royauté. Le palais témoigne de la place des royaumes dans l'histoire du Bénin contemporain.",
    savoirs: "Architecture de cour, organisation de l'espace royal, protocoles et rites de la royauté.",
    communities: "Famille royale de Porto-Novo, musée Honmè.",
    langues: "Goun, yoruba, français",
    personnalites: "Roi Toffa Ier",
    infos_pratiques: "Musée ouvert au public, visite guidée. Horaires et tarifs à confirmer sur place.",
    sources: ["Musée Honmè, Porto-Novo", "Direction du patrimoine culturel du Bénin"],
    recits: [],
    quiz: [
      { question: "Quels autres noms porte la ville de Porto-Novo ?", choices: ["Hogbonou et Adjatchè", "Abomey et Allada", "Djougou et Parakou"], answer: 0, explanation: "Porto-Novo est aussi appelée Hogbonou (en goun) et Adjatchè (en yoruba)." },
      { question: "Que signifie « Honmè » ?", choices: ["Au bord de l'eau", "À l'intérieur du palais", "La grande place"], answer: 1, explanation: "Honmè signifie « à l'intérieur du palais »." }
    ]
  },
  {
    id: 109,
    slug: "grande-mosquee-porto-novo",
    country: "Bénin",
    cat: "culturel",
    name: "Grande Mosquée de Porto-Novo",
    region: "Ouémé, Porto-Novo",
    featured: false,
    latitude: 6.4969,
    longitude: 2.628,
    radius: 400,
    themes: ["architecture", "spiritualites", "memoire-traite"],
    description: "Avec sa façade colorée, la Grande Mosquée de Porto-Novo est un exemple remarquable d'architecture afro-brésilienne, inspirée des églises baroques de Bahia.",
    histoire: "Elle a été construite au début du XXe siècle par des Agudas, Africains musulmans revenus du Brésil après l'abolition de l'esclavage. Ils ont rapporté les techniques et le style architectural des églises de Salvador de Bahia, ce qui explique cette façade étonnante pour une mosquée.",
    culture: "Le bâtiment raconte les allers-retours entre l'Afrique et les Amériques : une histoire de déportation, mais aussi de retour et de création culturelle.",
    savoirs: "Architecture afro-brésilienne : façades à pilastres, frontons et décors peints.",
    communities: "Communauté musulmane de Porto-Novo, descendants agudas.",
    langues: "Goun, yoruba, français",
    personnalites: "—",
    infos_pratiques: "Lieu de culte : visite de l'extérieur, ou de l'intérieur avec autorisation et en dehors des heures de prière. Tenue correcte exigée.",
    sources: ["Direction du patrimoine culturel du Bénin"],
    recits: [],
    quiz: [
      { question: "De quel pays les bâtisseurs de la Grande Mosquée de Porto-Novo avaient-ils rapporté leur style ?", choices: ["Du Brésil", "Du Maroc", "De l'Inde"], answer: 0, explanation: "Les Agudas, revenus du Brésil, se sont inspirés des églises baroques de Salvador de Bahia." }
    ]
  },
  {
    id: 110,
    slug: "chutes-de-kota",
    country: "Bénin",
    cat: "naturel",
    name: "Chutes de Kota",
    region: "Atacora, Natitingou",
    featured: false,
    latitude: 10.287,
    longitude: 1.452,
    radius: 1500,
    themes: ["eaux", "faune-flore"],
    description: "Près de Natitingou, les chutes de Kota tombent dans un bassin naturel au milieu de la végétation de l'Atacora. Un lieu de fraîcheur et de baignade apprécié.",
    histoire: "Les chutes se trouvent dans la chaîne de l'Atacora, qui traverse le nord-ouest du Bénin. Le site est devenu un lieu de détente et d'écotourisme géré avec les communautés locales.",
    culture: "Les cours d'eau et les rochers de l'Atacora sont parfois associés à des esprits et à des interdits locaux : se renseigner auprès des habitants.",
    savoirs: "Connaissance des plantes et des cycles de l'eau par les communautés voisines.",
    communities: "Villages voisins de Kota.",
    langues: "Ditammari, waama, français",
    personnalites: "—",
    infos_pratiques: "Accès par piste depuis Natitingou. Débit plus impressionnant en saison des pluies. Ne rien laisser sur place.",
    sources: ["Office du tourisme du Bénin — Atacora"],
    recits: [],
    quiz: [
      { question: "Dans quelle chaîne de montagnes se trouvent les chutes de Kota ?", choices: ["L'Atlas", "L'Atacora", "Le Fouta-Djallon"], answer: 1, explanation: "Les chutes de Kota se trouvent dans la chaîne de l'Atacora, près de Natitingou." },
      { question: "Quel geste adopter sur un site naturel ?", choices: ["Graver son nom sur les rochers", "Emporter ses déchets", "Cueillir des plantes en souvenir"], answer: 1, explanation: "On repart avec ses déchets et on laisse le site intact pour les autres visiteurs et pour la nature." }
    ]
  },
  {
    id: 111,
    slug: "lac-aheme-possotome",
    country: "Bénin",
    cat: "naturel",
    name: "Lac Ahémé et Possotomè",
    region: "Mono, Possotomè",
    featured: false,
    latitude: 6.47,
    longitude: 1.97,
    radius: 5000,
    themes: ["eaux", "gastronomie", "marches"],
    description: "Au bord du lac Ahémé, le village de Possotomè est connu pour sa source d'eau minérale et pour la vie des pêcheurs, qui pratiquent encore des techniques traditionnelles.",
    histoire: "Le lac Ahémé, relié à la mer par le chenal de l'Aho, est depuis longtemps une zone de pêche et d'échanges. Possotomè est devenue célèbre pour son eau minérale, commercialisée dans tout le pays.",
    culture: "La vie du lac rythme celle des villages : pêche, fumage et vente du poisson, fabrication des pirogues. Les communautés du lac entretiennent aussi des lieux de culte liés à l'eau.",
    savoirs: "Pêche en acadja, fabrication de filets et de nasses, fumage du poisson, connaissance des saisons du lac.",
    communities: "Pêcheurs et transformatrices de poisson des villages du lac.",
    langues: "Fon, xwla, français",
    personnalites: "—",
    infos_pratiques: "Balades en pirogue et visites de villages organisées localement. Se renseigner auprès des structures d'écotourisme de Possotomè.",
    sources: ["Agence nationale de promotion des patrimoines et de développement du tourisme (ANPT, Bénin)"],
    recits: [],
    quiz: [
      { question: "Pour quelle ressource Possotomè est-elle célèbre ?", choices: ["Son or", "Son eau minérale", "Son pétrole"], answer: 1, explanation: "La source de Possotomè fournit une eau minérale connue dans tout le Bénin." }
    ]
  },
  {
    id: 112,
    slug: "marche-dantokpa",
    country: "Bénin",
    cat: "culturel",
    name: "Marché Dantokpa",
    region: "Littoral, Cotonou",
    featured: false,
    latitude: 6.37,
    longitude: 2.433,
    radius: 700,
    themes: ["marches", "gastronomie", "artisanat"],
    description: "Au bord de la lagune de Cotonou, Dantokpa (« Tokpa ») est l'un des plus grands marchés à ciel ouvert d'Afrique de l'Ouest. On y trouve de tout : tissus, épices, produits vivriers, artisanat, objets de culte.",
    histoire: "Le marché s'est développé au XXe siècle au bord de la lagune, qui facilitait l'arrivée des marchandises par pirogue. Il est devenu un carrefour commercial pour le Bénin et les pays voisins, notamment le Nigéria.",
    culture: "Dantokpa est un monde en soi, animé en grande partie par des commerçantes. C'est le meilleur endroit pour découvrir les produits de la cuisine béninoise et les pagnes.",
    savoirs: "Savoir-faire commerciaux des « bonnes dames » du marché, circuits d'approvisionnement, produits de la pharmacopée traditionnelle.",
    communities: "Commerçantes et commerçants de Dantokpa.",
    langues: "Fon, goun, yoruba, mina, français",
    personnalites: "—",
    infos_pratiques: "Très grande affluence : venir accompagné, surveiller ses affaires, demander avant de photographier. Plus calme tôt le matin.",
    sources: ["Mairie de Cotonou"],
    recits: [],
    quiz: [
      { question: "Au bord de quelle étendue d'eau se trouve le marché Dantokpa ?", choices: ["Le lac Ahémé", "La lagune de Cotonou", "Le fleuve Niger"], answer: 1, explanation: "Dantokpa borde la lagune de Cotonou, qui facilitait autrefois l'arrivée des marchandises." },
      { question: "Quel accompagnement à base de farine de maïs est courant dans la cuisine béninoise ?", choices: ["La pâte (wɔ̌)", "Le couscous de blé", "Les pâtes italiennes"], answer: 0, explanation: "La pâte de maïs (wɔ̌ en fon) accompagne de nombreuses sauces." }
    ]
  },
  {
    id: 113,
    slug: "gaani-nikki",
    country: "Bénin",
    cat: "culturel",
    name: "Fête de la Gaani à Nikki",
    region: "Borgou, Nikki",
    featured: false,
    latitude: 9.94,
    longitude: 3.21,
    radius: 3000,
    themes: ["festivals", "royaumes", "musiques-danses"],
    description: "La Gaani est la grande fête annuelle des Baatonu (Bariba). À Nikki, siège historique du royaume, cavaliers en tenue d'apparat, musiciens et dignitaires célèbrent l'unité et l'identité du peuple.",
    histoire: "Nikki est le centre historique du royaume baatonu. La Gaani y rassemble chaque année le roi (Sina Boko), les princes et les communautés venues de tout le Borgou et au-delà. Sa date est fixée selon le calendrier lunaire.",
    culture: "Les chevaux, richement harnachés, sont au cœur de la fête : ils rappellent la tradition guerrière et cavalière des Baatonu. Tambours, trompes et chants de griots accompagnent les défilés.",
    savoirs: "Art équestre, confection des harnachements, musique de cour et généalogies chantées par les griots.",
    communities: "Royauté de Nikki, communautés baatonu du Borgou.",
    langues: "Baatonum, dendi, peul, français",
    personnalites: "—",
    infos_pratiques: "Date variable chaque année (calendrier lunaire) : se renseigner à l'avance. Forte affluence.",
    sources: ["Direction du patrimoine culturel du Bénin"],
    recits: [],
    quiz: [
      { question: "Quel animal est au cœur de la fête de la Gaani ?", choices: ["Le cheval", "Le chameau", "L'éléphant"], answer: 0, explanation: "Les cavaliers et leurs chevaux harnachés sont au centre de la fête, en souvenir de la tradition cavalière baatonu." },
      { question: "Quel peuple célèbre la Gaani ?", choices: ["Les Baatonu (Bariba)", "Les Fon", "Les Toffinu"], answer: 0, explanation: "La Gaani est la grande fête des Baatonu, dont Nikki est le centre historique." }
    ]
  }
];
