// Données de démonstration importées par « npm run db:seed ».
// Source unique : le frontend lit désormais tout depuis l'API.

// Pays mis en avant dans le prototype (drapeau et position approximative).
const COUNTRIES = [
  {name:"Bénin", flag:"🇧🇯", mapId:"204", lon:2.3, lat:9.3},
  {name:"Guinée", flag:"🇬🇳", mapId:"324", lon:-10.9, lat:10.4},
  {name:"Sénégal", flag:"🇸🇳", mapId:"686", lon:-14.5, lat:14.5},
  {name:"Côte d'Ivoire", flag:"🇨🇮", mapId:"384", lon:-5.5, lat:7.5},
  {name:"Ghana", flag:"🇬🇭", mapId:"288", lon:-1.2, lat:7.9},
  {name:"Togo", flag:"🇹🇬", mapId:"768", lon:1.2, lat:8.6},
  {name:"Mali", flag:"🇲🇱", mapId:"466", lon:-3.9, lat:17.6},
  {name:"Nigéria", flag:"🇳🇬", mapId:"566", lon:8.7, lat:9.1},
  {name:"Maroc", flag:"🇲🇦", mapId:"504", lon:-6, lat:31.8},
  {name:"Égypte", flag:"🇪🇬", mapId:"818", lon:30.8, lat:26.8},
  {name:"Kenya", flag:"🇰🇪", mapId:"404", lon:37.9, lat:0.2},
  {name:"Afrique du Sud", flag:"🇿🇦", mapId:"710", lon:24.7, lat:-30.6}
];

// Les 54 pays africains, avec leur code ISO 3166 numérique (utilisé par la carte).
const ALL_AFRICA_COUNTRIES = [
  ["Algérie","012"],["Angola","024"],["Bénin","204"],["Botswana","072"],["Burkina Faso","854"],
  ["Burundi","108"],["Cabo Verde","132"],["Cameroun","120"],["Comores","174"],["Congo","178"],
  ["Côte d'Ivoire","384"],["Djibouti","262"],["Égypte","818"],["Érythrée","232"],["Eswatini","748"],
  ["Éthiopie","231"],["Gabon","266"],["Gambie","270"],["Ghana","288"],["Guinée","324"],
  ["Guinée-Bissau","624"],["Guinée équatoriale","226"],["Kenya","404"],["Lesotho","426"],["Libéria","430"],
  ["Libye","434"],["Madagascar","450"],["Malawi","454"],["Mali","466"],["Maroc","504"],
  ["Maurice","480"],["Mauritanie","478"],["Mozambique","508"],["Namibie","516"],["Niger","562"],
  ["Nigéria","566"],["Ouganda","800"],["République centrafricaine","140"],["République démocratique du Congo","180"],
  ["Rwanda","646"],["São Tomé-et-Príncipe","678"],["Sénégal","686"],["Seychelles","690"],["Sierra Leone","694"],
  ["Somalie","706"],["Soudan","729"],["Soudan du Sud","728"],["Tanzanie","834"],["Tchad","148"],
  ["Togo","768"],["Tunisie","788"],["Zambie","894"],["Zimbabwe","716"],["Afrique du Sud","710"]
];

// Fiches des autres pays, issues du premier prototype. Elles sont importées
// en brouillon (non visibles du public) : le prototype se concentre sur le
// Bénin et la Guinée (voir db/content/). Un administrateur peut les publier.
const SITES = [
  {id:7,country:"Sénégal",cat:"historique",name:"Île de Gorée",region:"Dakar",featured:true,
   description:"Petite île au large de Dakar, lieu de mémoire majeur de la traite négrière transatlantique.",
   histoire:"La Maison des Esclaves y symbolise le départ forcé de millions d'Africains vers les Amériques.",
   culture:"Lieu de recueillement et de pèlerinage mémoriel, classé patrimoine mondial de l'UNESCO.",
   savoirs:"Transmission de la mémoire de la traite auprès des jeunes générations.",
   communities:"Habitants de l'île, guides mémoriels.",langues:"Wolof, français",personnalites:"—",sources:"UNESCO — à compléter."},
  {id:8,country:"Sénégal",cat:"naturel",name:"Lac Rose (Lac Retba)",region:"Dakar",
   description:"Lac dont l'eau prend une teinte rosée due à une algue riche en bêta-carotène, ancien point d'arrivée du Rallye Dakar.",
   histoire:"Exploité depuis des décennies pour l'extraction artisanale du sel.",
   culture:"Symbole touristique du Sénégal, lieu de vie des extracteurs de sel.",
   savoirs:"Techniques traditionnelles d'extraction et de conservation du sel.",
   communities:"Coopératives d'extracteurs de sel.",langues:"Wolof, français",personnalites:"—",sources:"Office sénégalais du tourisme — à compléter."},
  {id:9,country:"Sénégal",cat:"culturel",name:"Île de Saint-Louis",region:"Saint-Louis",
   description:"Ancienne capitale coloniale à l'architecture particulière, entre fleuve Sénégal et océan Atlantique.",
   histoire:"Première ville fondée par les Français en Afrique de l'Ouest, classée patrimoine mondial.",
   culture:"Connue pour son festival de jazz et son métissage architectural.",
   savoirs:"Savoir-faire de la pêche traditionnelle sur pirogues colorées.",
   communities:"Pêcheurs Guet-Ndariens, association de sauvegarde du patrimoine.",langues:"Wolof, français",personnalites:"—",sources:"UNESCO — à compléter."},

  {id:10,country:"Côte d'Ivoire",cat:"historique",name:"Basilique de Yamoussoukro",region:"Yamoussoukro",
   description:"Plus grande basilique du monde par sa superficie, inspirée de Saint-Pierre de Rome.",
   histoire:"Construite dans les années 1980 à l'initiative du président Félix Houphouët-Boigny.",
   culture:"Symbole architectural majeur de la capitale politique ivoirienne.",
   savoirs:"Savoir-faire artisanal du vitrail et de la sculpture religieuse.",
   communities:"Diocèse de Yamoussoukro.",langues:"Baoulé, français",personnalites:"Félix Houphouët-Boigny",sources:"À compléter."},
  {id:11,country:"Côte d'Ivoire",cat:"naturel",name:"Parc national de Taï",region:"Sud-Ouest",featured:true,
   description:"Une des dernières grandes forêts primaires d'Afrique de l'Ouest, riche en biodiversité.",
   histoire:"Classé réserve de biosphère puis patrimoine mondial de l'UNESCO.",
   culture:"Terre de communautés forestières vivant de la forêt depuis des générations.",
   savoirs:"Connaissances sur les chimpanzés utilisateurs d'outils, pratiques de conservation.",
   communities:"Communautés riveraines, chercheurs en primatologie.",langues:"Français",personnalites:"—",sources:"UNESCO — à compléter."},
  {id:12,country:"Côte d'Ivoire",cat:"culturel",name:"Grand-Bassam",region:"Sud-Comoé",
   description:"Ancienne capitale coloniale, ville historique au bord de l'océan, architecture coloniale préservée.",
   histoire:"Première capitale de la Côte d'Ivoire française, abandonnée après une épidémie de fièvre jaune.",
   culture:"Ville d'art et d'artisanat, quartier France classé au patrimoine mondial.",
   savoirs:"Artisanat local, sculpture sur bois.",
   communities:"Association des artisans de Grand-Bassam.",langues:"Français, dioula",personnalites:"—",sources:"UNESCO — à compléter."},

  {id:13,country:"Ghana",cat:"historique",name:"Château de Cape Coast",region:"Cape Coast",featured:true,
   description:"Ancien comptoir et fort colonial, l'un des principaux points de départ de la traite négrière transatlantique.",
   histoire:"Construit par les Suédois puis repris par les Britanniques, il servit de centre de détention d'esclaves.",
   culture:"Lieu de mémoire majeur, visité chaque année par des descendants de la diaspora.",
   savoirs:"Transmission de la mémoire de la traite négrière.",
   communities:"Communauté locale de Cape Coast, guides mémoriels.",langues:"Fante, anglais",personnalites:"—",sources:"UNESCO — à compléter."},
  {id:14,country:"Ghana",cat:"historique",name:"Fort d'Elmina",region:"Elmina",
   description:"Plus ancien édifice colonial européen d'Afrique subsaharienne, construit par les Portugais en 1482.",
   histoire:"Utilisé successivement pour le commerce de l'or puis pour la traite négrière.",
   culture:"Site classé au patrimoine mondial de l'UNESCO, lieu de mémoire.",
   savoirs:"Histoire du commerce transatlantique et de la résistance.",
   communities:"Communauté de pêcheurs d'Elmina.",langues:"Fante, anglais",personnalites:"—",sources:"UNESCO — à compléter."},
  {id:15,country:"Ghana",cat:"naturel",name:"Lac Volta",region:"Est du Ghana",
   description:"L'un des plus grands lacs artificiels du monde, formé par le barrage d'Akosombo.",
   histoire:"Créé dans les années 1960 pour la production d'électricité et l'irrigation.",
   culture:"Vie économique locale organisée autour de la pêche et du transport lacustre.",
   savoirs:"Pêche traditionnelle, savoirs liés à la gestion de l'eau.",
   communities:"Communautés de pêcheurs riveraines.",langues:"Ewe, anglais",personnalites:"—",sources:"À compléter."},

  {id:16,country:"Togo",cat:"culturel",name:"Koutammakou (Pays Batammariba)",region:"Nord-Togo",featured:true,
   description:"Paysage culturel des Batammariba, connu pour ses cases-tours en terre (Takienta) uniques en Afrique.",
   histoire:"Habité par les Batammariba depuis plusieurs siècles, préservant un mode de vie traditionnel.",
   culture:"Classé au patrimoine mondial de l'UNESCO pour son architecture et son organisation sociale.",
   savoirs:"Architecture en terre, rites de passage, cosmogonie batammariba.",
   communities:"Communauté batammariba.",langues:"Ditammari, français",personnalites:"—",sources:"UNESCO — à compléter."},
  {id:17,country:"Togo",cat:"naturel",name:"Lac Togo",region:"Région Maritime",
   description:"Lagune côtière prisée pour les activités nautiques et son cadre naturel calme.",
   histoire:"Longtemps un lieu de pêche et d'échanges commerciaux locaux.",
   culture:"Village d'Agbodrafo et son passé lié à la traite négrière à proximité.",
   savoirs:"Pêche lagunaire, tressage de filets.",
   communities:"Pêcheurs riverains du lac.",langues:"Éwé, français",personnalites:"—",sources:"À compléter."},
  {id:18,country:"Togo",cat:"savoirs",name:"Marché des féticheurs d'Akodessewa",region:"Lomé",
   description:"Marché traditionnel consacré à la pharmacopée et aux pratiques du culte vodun.",
   histoire:"Fonctionne depuis des générations comme centre de savoirs traditionnels vodun.",
   culture:"Lieu central des pratiques spirituelles vodun au Togo.",
   savoirs:"Pharmacopée traditionnelle, connaissances botaniques et rituelles.",
   communities:"Guérisseurs traditionnels, prêtres vodun.",langues:"Éwé, français",personnalites:"—",sources:"À compléter."},

  {id:19,country:"Mali",cat:"historique",name:"Tombouctou",region:"Nord du Mali",featured:true,
   description:"Ancienne cité savante médiévale, carrefour caravanier et centre intellectuel de l'islam en Afrique de l'Ouest.",
   histoire:"Abrite des milliers de manuscrits anciens témoignant d'une riche tradition scientifique et religieuse.",
   culture:"Ville classée au patrimoine mondial de l'UNESCO, mausolées et mosquées de terre.",
   savoirs:"Manuscrits anciens, astronomie, droit islamique, médecine traditionnelle.",
   communities:"Familles de gardiens de manuscrits, érudits locaux.",langues:"Songhaï, tamasheq, français",personnalites:"—",sources:"UNESCO — à compléter."},
  {id:20,country:"Mali",cat:"culturel",name:"Falaise de Bandiagara (Pays Dogon)",region:"Mopti",
   description:"Falaise spectaculaire abritant les villages dogons, célèbres pour leur architecture et leur cosmogonie.",
   histoire:"Habité depuis des siècles, refuge historique face aux invasions successives.",
   culture:"Cosmogonie dogon complexe, masques et danses rituelles reconnues mondialement.",
   savoirs:"Architecture troglodyte, astronomie traditionnelle, agriculture en terrasses.",
   communities:"Communauté dogon.",langues:"Dogon, français",personnalites:"—",sources:"UNESCO — à compléter."},
  {id:21,country:"Mali",cat:"historique",name:"Grande Mosquée de Djenné",region:"Djenné",
   description:"Plus grand édifice en terre crue du monde, chef-d'œuvre de l'architecture soudano-sahélienne.",
   histoire:"Reconstruite au début du XXe siècle sur le site d'une mosquée du XIIIe siècle.",
   culture:"Cœur spirituel de la ville de Djenné, entretenue chaque année par la population.",
   savoirs:"Architecture en banco, techniques de crépissage collectif annuel.",
   communities:"Population de Djenné, corporation des maçons.",langues:"Bambara, français",personnalites:"—",sources:"UNESCO — à compléter."},

  {id:22,country:"Nigéria",cat:"historique",name:"Murs de Bénin City",region:"État d'Edo",
   description:"Vestiges des anciens remparts du puissant royaume du Bénin, l'une des plus grandes structures faites de main d'homme.",
   histoire:"Édifiés à partir du XIIIe siècle pour protéger la capitale du royaume du Bénin.",
   culture:"Témoin de l'un des royaumes les plus sophistiqués d'Afrique précoloniale, connu pour ses bronzes.",
   savoirs:"Art du bronze, organisation urbaine et politique du royaume.",
   communities:"Palais royal d'Edo, historiens locaux.",langues:"Edo, anglais",personnalites:"Oba d'Edo",sources:"À compléter."},
  {id:23,country:"Nigéria",cat:"naturel",name:"Rochers d'Idanre",region:"État d'Ondo",featured:true,
   description:"Collines rocheuses sacrées surplombant la ville historique d'Idanre, accessibles par des marches ancestrales.",
   histoire:"Ancien site de peuplement yoruba, refuge historique en cas de conflit.",
   culture:"Considérées comme sacrées, associées à des divinités et légendes locales.",
   savoirs:"Connaissances géologiques et légendes de peuplement transmises oralement.",
   communities:"Communauté yoruba d'Idanre.",langues:"Yoruba, anglais",personnalites:"—",sources:"À compléter."},
  {id:24,country:"Nigéria",cat:"savoirs",name:"Bois sacré d'Osun-Osogbo",region:"État d'Osun",
   description:"Forêt sacrée dédiée à la déesse yoruba Osun, ponctuée de sanctuaires et de sculptures.",
   histoire:"Lieu de culte continu depuis des siècles, encore vivant aujourd'hui.",
   culture:"Cœur du culte yoruba d'Osun, festival annuel rassemblant des milliers de fidèles.",
   savoirs:"Pharmacopée traditionnelle, art sacré yoruba, rites de fertilité.",
   communities:"Prêtresses et prêtres du culte d'Osun.",langues:"Yoruba, anglais",personnalites:"—",sources:"UNESCO — à compléter."},

  {id:25,country:"Maroc",cat:"culturel",name:"Médina de Fès",region:"Fès",featured:true,
   description:"L'une des plus grandes zones piétonnes urbaines du monde, dédale de ruelles, souks et médersas.",
   histoire:"Fondée au IXe siècle, ancienne capitale intellectuelle et spirituelle du Maroc.",
   culture:"Abrite l'université Al Quaraouiyine, l'une des plus anciennes au monde encore en activité.",
   savoirs:"Artisanat du cuir, de la céramique et du travail du métal transmis de génération en génération.",
   communities:"Corporations d'artisans de la médina.",langues:"Arabe, amazigh, français",personnalites:"—",sources:"UNESCO — à compléter."},
  {id:26,country:"Maroc",cat:"historique",name:"Kasbah d'Aït-Ben-Haddou",region:"Ouarzazate",
   description:"Ksar fortifié en pisé, ancienne étape caravanière entre le Sahara et Marrakech.",
   histoire:"Construit à partir du XVIIe siècle le long d'une route commerciale transsaharienne majeure.",
   culture:"Exemple emblématique de l'architecture en terre du sud marocain.",
   savoirs:"Techniques de construction en pisé et en adobe.",
   communities:"Familles habitant encore une partie du ksar.",langues:"Amazigh, arabe, français",personnalites:"—",sources:"UNESCO — à compléter."},
  {id:27,country:"Maroc",cat:"culturel",name:"Chefchaouen",region:"Rif",
   description:"Ville aux murs peints en bleu, nichée dans les montagnes du Rif.",
   histoire:"Fondée au XVe siècle, refuge historique pour les populations andalouses et juives.",
   culture:"Identité visuelle unique, mélange d'influences amazighes, arabes et andalouses.",
   savoirs:"Tissage traditionnel de la laine, artisanat local.",
   communities:"Population locale amazighe et andalouse.",langues:"Amazigh, arabe, français",personnalites:"—",sources:"À compléter."},

  {id:28,country:"Égypte",cat:"historique",name:"Pyramides de Gizeh",region:"Gizeh",featured:true,
   description:"Dernière des sept merveilles du monde antique encore debout, complexe funéraire monumental.",
   histoire:"Construites il y a environ 4500 ans pour les pharaons de la IVe dynastie.",
   culture:"Symbole mondial de la civilisation égyptienne antique.",
   savoirs:"Ingénierie et astronomie de l'Égypte ancienne.",
   communities:"Autorités du patrimoine égyptien.",langues:"Arabe",personnalites:"Khéops, Khéphren, Mykérinos",sources:"UNESCO — à compléter."},
  {id:29,country:"Égypte",cat:"historique",name:"Vallée des Rois",region:"Louxor",
   description:"Nécropole royale du Nouvel Empire abritant les tombeaux richement décorés des pharaons.",
   histoire:"Utilisée pendant environ 500 ans comme lieu de sépulture des pharaons et nobles.",
   culture:"Site archéologique majeur, dont la tombe de Toutankhamon découverte en 1922.",
   savoirs:"Peinture funéraire, hiéroglyphes, rites funéraires égyptiens.",
   communities:"Autorités archéologiques, guides locaux.",langues:"Arabe",personnalites:"Toutankhamon, Ramsès II",sources:"UNESCO — à compléter."},
  {id:30,country:"Égypte",cat:"historique",name:"Temple d'Abou Simbel",region:"Nubie",
   description:"Temples monumentaux taillés dans la roche par Ramsès II, déplacés pierre par pierre au XXe siècle.",
   histoire:"Construits au XIIIe siècle av. J.-C., sauvés des eaux du barrage d'Assouan par un déplacement spectaculaire.",
   culture:"Symbole du génie architectural égyptien et d'un sauvetage patrimonial international.",
   savoirs:"Astronomie appliquée à l'architecture, sculpture monumentale.",
   communities:"Communauté nubienne.",langues:"Arabe, nubien",personnalites:"Ramsès II",sources:"UNESCO — à compléter."},

  {id:31,country:"Kenya",cat:"naturel",name:"Réserve du Maasai Mara",region:"Vallée du Rift",featured:true,
   description:"Réserve emblématique de la grande migration annuelle des gnous et des zèbres.",
   histoire:"Terre ancestrale du peuple Maasaï, réserve protégée depuis le milieu du XXe siècle.",
   culture:"Forte présence culturelle maasaï autour de la réserve.",
   savoirs:"Savoirs pastoraux et connaissance approfondie de la faune sauvage.",
   communities:"Communauté maasaï, guides et rangers locaux.",langues:"Maa, swahili, anglais",personnalites:"—",sources:"À compléter."},
  {id:32,country:"Kenya",cat:"historique",name:"Fort Jesus",region:"Mombasa",
   description:"Forteresse construite par les Portugais au XVIe siècle pour contrôler la route commerciale de l'océan Indien.",
   histoire:"Successivement occupé par Portugais, Omanais et Britanniques au fil des siècles.",
   culture:"Témoin des échanges swahili-arabo-portugais sur la côte est-africaine.",
   savoirs:"Architecture militaire, histoire du commerce dans l'océan Indien.",
   communities:"Communauté swahili de Mombasa.",langues:"Swahili, anglais",personnalites:"—",sources:"UNESCO — à compléter."},
  {id:33,country:"Kenya",cat:"naturel",name:"Lac Nakuru",region:"Vallée du Rift",
   description:"Lac alcalin connu pour ses immenses colonies de flamants roses et sa riche faune.",
   histoire:"Classé parc national dès 1961 pour protéger l'écosystème du lac.",
   culture:"Site emblématique du tourisme de nature au Kenya.",
   savoirs:"Connaissances écologiques sur les lacs alcalins de la vallée du Rift.",
   communities:"Services des parcs nationaux du Kenya.",langues:"Swahili, anglais",personnalites:"—",sources:"À compléter."},

  {id:34,country:"Afrique du Sud",cat:"historique",name:"Robben Island",region:"Le Cap",featured:true,
   description:"Île-prison au large du Cap, tristement célèbre pour avoir enfermé des opposants à l'apartheid.",
   histoire:"Nelson Mandela y fut emprisonné pendant 18 des 27 années de sa détention.",
   culture:"Symbole mondial de la lutte contre l'apartheid et de la réconciliation.",
   savoirs:"Histoire de la résistance politique sud-africaine.",
   communities:"Fondation Robben Island, anciens prisonniers guides.",langues:"Xhosa, afrikaans, anglais",personnalites:"Nelson Mandela",sources:"UNESCO — à compléter."},
  {id:35,country:"Afrique du Sud",cat:"naturel",name:"Montagne de la Table",region:"Le Cap",
   description:"Massif emblématique surplombant Le Cap, souvent couvert d'une nappe de nuages caractéristique.",
   histoire:"Repère historique pour les navigateurs depuis plusieurs siècles.",
   culture:"Symbole visuel de la ville du Cap et de l'Afrique du Sud.",
   savoirs:"Biodiversité unique du fynbos, flore endémique protégée.",
   communities:"Parc national de la Montagne de la Table.",langues:"Afrikaans, xhosa, anglais",personnalites:"—",sources:"À compléter."},
  {id:36,country:"Afrique du Sud",cat:"savoirs",name:"Berceau de l'Humanité",region:"Gauteng",
   description:"Ensemble de sites archéologiques ayant livré certains des plus anciens fossiles d'hominidés connus.",
   histoire:"Fouilles menées depuis le début du XXe siècle, dont la découverte du fossile « Little Foot ».",
   culture:"Site clé pour comprendre les origines de l'humanité en Afrique.",
   savoirs:"Paléoanthropologie, datation des fossiles, évolution humaine.",
   communities:"Instituts de recherche paléoanthropologique.",langues:"Afrikaans, anglais",personnalites:"—",sources:"UNESCO — à compléter."}
];

module.exports = { COUNTRIES, ALL_AFRICA_COUNTRIES, SITES };
